(function(){'use strict';function ready(){var d=document,p=location.pathname.split('/').pop().replace('.html','')||'mrkim-signal';d.body.classList.add('brand-v93','v93-'+p);var logo=d.querySelector('header .logo');if(logo&&!d.querySelector('.v93-beta')){var beta=d.createElement('span');beta.className='v93-beta';beta.textContent='🧪 Beta';beta.setAttribute('aria-label','베타 버전');logo.append(beta);}d.querySelectorAll('main .pg-h1,.v86-page-head h1').forEach(function(n){n.classList.add('v93-title');});d.querySelectorAll('.stock-eyebrow,.v86-eyebrow').forEach(function(n){n.textContent='Mr.Kim Signal · 시장 리서치';});if(p==='kr-stock'||p==='crypto'){var tools=d.getElementById('unified-tools');if(tools&&!tools.parentElement.classList.contains('v93-personal-wrap')){var wrap=d.createElement('div');wrap.className='wrap v93-personal-wrap';tools.before(wrap);wrap.append(tools);var guide=d.getElementById('guide');if(guide)wrap.append(guide);}}
if(p==='trade'){var cards=Array.from(d.querySelectorAll('.strat .scard'));cards.forEach(function(card){var b=card.querySelector('[data-sc]');if(b)b.addEventListener('click',function(){if(card.classList.contains('open'))return;cards.forEach(function(other){if(other===card)return;other.classList.remove('open');var button=other.querySelector('[data-sc]');if(button){button.textContent='펼치기';button.setAttribute('aria-expanded','false');}});},true);});}
if(p==='p2p'){function decorate(){d.querySelectorAll('#p2p-open-list .p2p-card').forEach(function(card){card.classList.add('v93-product');if(card.parentElement.style.display==='grid')card.parentElement.classList.add('v93-product-grid');});}decorate();var list=d.getElementById('p2p-open-list');if(list)new MutationObserver(decorate).observe(list,{childList:true,subtree:true});}
enhance(p);}
function enhance(p){var d=document,labels={'stock':'미국주식','kr-stock':'한국주식','crypto':'가상화폐','bond':'채권','finprod':'금융상품','ipo':'공모주','p2p':'P2P','fx':'환율','trade':'매매김군','mrkim-signal':'홈'},name=labels[p]||p;
var guide=d.querySelector('.market-help');if(guide){var section=d.createElement('section');section.className='v94-guide';var heading=d.createElement('h2');heading.textContent='지표 읽는 법 (용어 가이드)';var button=d.createElement('button');button.type='button';button.className='v94-help';button.textContent='Help ⓘ';button.setAttribute('aria-expanded','false');heading.append(button);var content=d.createElement('div');content.className='v94-guide-content';content.hidden=true;Array.from(guide.children).forEach(function(n){if(n.tagName!=='SUMMARY')content.append(n);});section.append(heading,content);guide.replaceWith(section);button.onclick=function(){function toggle(){content.hidden=!content.hidden;button.setAttribute('aria-expanded',String(!content.hidden));}if(content.hidden&&window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(toggle);else toggle();};}
var history=d.getElementById('v92-update-history');if(!history){history=d.createElement('details');history.id='v92-update-history';d.querySelector('footer').append(history);}history.replaceChildren();var summary=d.createElement('summary');summary.textContent='🗓️ 업데이트 이력';history.append(summary);var records=[['2026-10-11','v94','로고·Beta·제목 통일, 용어가이드 및 관리자 업데이트 이력 정리']];if(p==='stock')records.push(['2026-10-11','v94','사용량 보기를 관리자모드 해제 옆에 배치'],['2026-10-11','v92','공포탐욕 최근 흐름·하단 사용량 개선']);if(p==='kr-stock')records.push(['2026-10-11','v93','투자도구 왼쪽 정렬·한글 종목명·3종목 비교'],['2026-10-11','v92','기간 탭·실제 수신 점수 흐름·상세 표 개선'],['2026-10-11','v91','한글 검색·시장 지표·Help 개선']);if(p==='crypto')records.push(['2026-10-11','v94','한글 코인명 검색·왼쪽 투자도구·3종목 비교'],['2026-10-11','v92','현재 지수 제목·글로벌 트렌드 정렬']);if(p==='p2p')records.push(['2026-10-11','v93','오픈예정 상품 카드·일정 표시·제목 효과 개선']);if(p==='trade')records.push(['2026-10-11','v93','전략 3열·개별 상세 펼침·상단 잘림 개선']);if(!['stock','kr-stock','mrkim-signal'].includes(p))records.push(['2026-10-11','v92','제목 옆 화면관리 버튼·상단 탭줄 정리'],['2026-10-11','v90','표·카드·모바일 간격 통일']);
if(p==='stock'){var legacy=d.getElementById('stock-update-history');if(legacy)legacy.querySelectorAll('li').forEach(function(li){records.push(['2026-10-10','기존',li.textContent]);});}
records.sort(function(a,b){return b[0].localeCompare(a[0])||Number(b[1].slice(1))-Number(a[1].slice(1));});Array.from(new Set(records.map(function(r){return r[0];}))).forEach(function(date){var group=d.createElement('details'),s=d.createElement('summary'),list=d.createElement('ul');s.textContent=date+' · '+name;records.filter(function(r){return r[0]===date;}).forEach(function(r){var li=d.createElement('li');li.textContent=r[1]+' · '+r[2];list.append(li);});group.append(s,list);history.append(group);});
function sync(){var admin=false;try{admin=localStorage.getItem('mk_gate_off')==='1';}catch(e){}history.hidden=!admin;if(!admin)history.open=false;d.querySelectorAll('.cross-update,#stock-update-footer').forEach(function(b){b.hidden=!admin;if(b.tagName==='BUTTON')b.textContent='🗓️ 업데이트 · 2026.10.11';});if(p==='stock'){var bar=d.getElementById('mk-admin-bar'),usage=d.getElementById('v92-usage');if(bar&&usage&&!bar.querySelector('.v94-usage-button')){var b=d.createElement('button');b.type='button';b.className='v94-usage-button';b.textContent='📊 사용량 보기';bar.append(b);b.onclick=function(){usage.open=!usage.open;usage.hidden=!admin;if(usage.open)usage.scrollIntoView({behavior:'smooth',block:'center'});};}if(usage)usage.classList.add('v94-usage');}}
sync();setInterval(sync,1500);window.addEventListener('storage',sync);var update=d.querySelector('.cross-update');if(p==='mrkim-signal'&&update)update.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();if(!history.hidden)history.open=!history.open;},true);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();})();
