(function(){
 'use strict';var market=location.pathname.split('/').pop().replace('.html','');if(market!=='crypto'||document.getElementById('unified-tools'))return;
 var main=document.querySelector('main');if(!main)return;
 var $=function(s,r){return(r||document).querySelector(s);},esc=function(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});},RE=/^[A-Z0-9.^=\-]{1,20}$/;
 function permit(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function read(key,fallback){try{return JSON.parse((key==='mk_hold_'+market&&localStorage.getItem('stock_account_persist_'+market)!=='1'&&!localStorage.getItem(key)?sessionStorage:localStorage).getItem(key)||'null')||fallback;}catch(e){return fallback;}}
 function save(key,v){try{(key==='mk_hold_'+market&&localStorage.getItem('stock_account_persist_'+market)!=='1'?sessionStorage:localStorage).setItem(key,JSON.stringify(v));}catch(e){}}
 function money(n,c){return Number.isFinite(n)?new Intl.NumberFormat('ko-KR',{style:'currency',currency:c||'USD',maximumFractionDigits:c==='KRW'?0:2}).format(n):'—';}
 function pct(n){return Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'—';}

 RE=market==='kr-stock'?/^[A-Z0-9]+\.(KS|KQ)$/:/^[A-Z0-9]+-(USD|KRW|USDT)$/;
 // Copy matching prior entries without changing or deleting the original US data.
 try{['mk_my_tickers','mk_hold'].forEach(function(k){[localStorage,sessionStorage].forEach(function(storage){var target=k+'_'+market;if(storage.getItem(target)!==null)return;var old=JSON.parse(storage.getItem(k)||'null');if(!old)return;var value=k==='mk_my_tickers'?old.filter(function(t){return RE.test(t);}):Object.fromEntries(Object.entries(old).filter(function(x){return RE.test(x[0]);}));storage.setItem(target,JSON.stringify(value));});});var pk='stock_account_persist_'+market;if(localStorage.getItem(pk)===null)localStorage.setItem(pk,localStorage.getItem('stock_account_persist')||'0');}catch(e){}
 var krNames={'BTC-USD':'비트코인','ETH-USD':'이더리움','XRP-USD':'리플','SOL-USD':'솔라나','BNB-USD':'비앤비','DOGE-USD':'도지코인','ADA-USD':'에이다','AVAX-USD':'아발란체','TRX-USD':'트론','LINK-USD':'체인링크','DOT-USD':'폴카닷','BCH-USD':'비트코인캐시','LTC-USD':'라이트코인','SUI-USD':'수이','SHIB-USD':'시바이누','TON11419-USD':'톤코인','USDT-USD':'테더','USDC-USD':'유에스디코인'};
 function norm(s){return String(s).trim().replace(/\s+/g,'').toUpperCase();}
 async function candidates(q){var key=norm(q),rows=Object.keys(krNames).map(function(t){return{symbol:t,name:krNames[t]};});document.querySelectorAll('.wl-row[data-t]').forEach(function(row){var t=row.dataset.t,n=row.querySelector('.wl-name a');if(RE.test(t)&&n&&!krNames[t]&&/[가-힣]/.test(n.textContent)){krNames[t]=n.textContent.trim();rows.push({symbol:t,name:krNames[t]});}});return rows.filter(function(r){return norm(r.name).includes(key)||norm(r.symbol).includes(key)||norm(r.symbol.split('-')[0])===key;});}
 async function resolveSymbol(v){v=v.trim();if(RE.test(v.toUpperCase()))return v.toUpperCase();var rows=await candidates(v),exact=rows.filter(function(r){return norm(r.name)===norm(v)||r.symbol.split('-')[0]===norm(v);});if(exact.length===1)return exact[0].symbol;if(rows.length===1)return rows[0].symbol;if(rows.length>1)throw Error('여러 코인이 검색되었습니다. 후보에서 선택해 주세요.');throw Error('등록된 한글 코인명 또는 BTC-USD 형식으로 입력해 주세요.');}
 window.MK_CRYPTO_RESOLVE_SYMBOL=resolveSymbol;
 async function domesticName(t,fallback){return krNames[t]||'코인명 미수신';}
 var cache={};
 async function quote(t,range){var key=t+'|'+(range||'1y');if(cache[key]&&Date.now()-cache[key].at<60000)return cache[key].data;var url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(t)+'?range='+(range||'1y')+'&interval=1d';var j=typeof getJSON==='function'?await getJSON(url):await fetch('https://ai.coolzet.workers.dev/?url='+encodeURIComponent(url)).then(function(r){if(!r.ok)throw Error('조회 실패');return r.json();});var r=j&&j.chart&&j.chart.result&&j.chart.result[0];if(!r)throw Error('조회 실패');var cl=r.indicators.quote[0].close,points=r.timestamp.map(function(ts,i){return{t:ts*1000,v:cl[i],d:new Date(ts*1000).toISOString().slice(0,10)};}).filter(function(x){return Number.isFinite(x.v)&&x.v>0;});if(!points.length)throw Error('시세 없음');var px=r.meta.regularMarketPrice||points[points.length-1].v,day=new Date((r.meta.regularMarketTime||r.timestamp[r.timestamp.length-1])*1000).toISOString().slice(0,10),older=points.filter(function(p){return p.d<day;}),prev=older.length?older[older.length-1].v:null;var result={t:t,name:await domesticName(t,r.meta.longName||r.meta.shortName),currency:r.meta.currency||'USD',px:px,pct:prev?100*(px/prev-1):null,points:points};cache[key]={at:Date.now(),data:result};return result;}
 var hub=document.createElement('details');hub.id='unified-tools';hub.className='unified-tools';hub.innerHTML='<summary>내 투자 도구</summary><nav aria-label="내 투자 도구"><button type="button" data-tool="watch" aria-pressed="true">☆ 관심종목</button><button type="button" data-tool="account" aria-pressed="false">▣ 내계좌</button><button type="button" data-tool="compare" aria-pressed="false">⌕ 종목비교</button></nav><p class="ut-hint">'+(market==='kr-stock'?'한국주식 BTC-USD · 코스닥 035900.KQ':'가상화폐 BTC-USD · ETH-USD')+'<br>관심종목·계좌는 이 시장 전용으로 별도 저장됩니다.</p><section data-panel="watch"><h3>내 관심종목</h3><form><label>종목 티커<input name="ticker" required maxlength="20" placeholder="'+(market==='kr-stock'?'BTC-USD':'BTC-USD')+'"></label><button>＋ 추가</button></form><div class="ut-watch" role="status"></div></section><section data-panel="account" hidden><h3>내계좌 · 손익·비중</h3><form><label>종목 티커<input name="ticker" required maxlength="20"></label><label>보유 수량<input name="quantity" type="number" min="0.00000001" step="any" required></label><label>평균단가 · 해당 종목 통화<input name="cost" type="number" min="0" step="any" required></label><button>＋ 추가·수정</button></form><label class="ut-save"><input type="checkbox">이 기기에 계좌 정보 계속 저장</label><p class="ut-hint">평가금액·손익·비중은 통화별로 계산합니다. 통화가 다른 종목을 합산하지 않습니다.</p><div class="ut-account" role="status"></div><label>수익률 기간<select class="ut-account-period"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button type="button" class="ut-account-curve">계좌 수익률 곡선</button><div class="ut-account-chart" role="status"></div></section><section data-panel="compare" hidden><h3>종목비교 · 수익률 곡선</h3><form><label>비교 종목 · 최대 3개<input name="symbols" placeholder="'+(market==='kr-stock'?'BTC-USD, 000660.KS':'BTC-USD, ETH-USD')+'" required></label><label>기간<select name="months"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button>비교하기</button></form><div class="ut-compare-chart" role="status"></div></section><p class="ut-message" role="status" aria-live="polite"></p></details>';main.appendChild(hub);
 hub.querySelector('summary').addEventListener('click',function(e){if(hub.open)return;e.preventDefault();permit(function(){hub.open=true;});});
 hub.querySelector('nav').addEventListener('click',function(e){var b=e.target.closest('[data-tool]');if(!b)return;hub.querySelectorAll('[data-panel]').forEach(function(p){p.hidden=p.dataset.panel!==b.dataset.tool;});hub.querySelectorAll('[data-tool]').forEach(function(x){x.setAttribute('aria-pressed',String(x===b));});if(b.dataset.tool==='watch')watch();if(b.dataset.tool==='account')account();});
 function message(s){$('.ut-message',hub).textContent=s;}
 var watchSeq=0;
 async function watch(){var seq=++watchSeq,list=read('mk_my_tickers_'+market,[]).filter(function(t){return RE.test(t);}).slice(0,20),box=$('.ut-watch',hub);if(!list.length){box.textContent='종목을 추가하면 가격과 등락률이 표시됩니다.';return;}box.textContent='관심종목 시세를 불러오는 중…';var results=await Promise.all(list.map(async function(t){try{return await quote(t);}catch(e){return {t:t,name:await domesticName(t)};}}));if(seq!==watchSeq)return;box.innerHTML=results.map(function(r){return '<div class="ut-row"><b class="ut-name" title="'+esc(r.t)+'">'+esc(r.name||'종목명 미수신')+'</b><div class="ut-spark">'+spark(r.points)+'</div><div><b>'+money(r.px,r.currency)+'</b><strong>'+pct(r.pct)+'</strong></div><button type="button" data-remove-watch="'+esc(r.t)+'" aria-label="'+esc(r.t)+' 삭제">×</button></div>';}).join('');}
 function spark(points){if(!points||points.length<2)return '';var a=points.slice(-30),lo=Math.min.apply(null,a.map(function(p){return p.v;})),hi=Math.max.apply(null,a.map(function(p){return p.v;})),d=a.map(function(p,i){return(i?'L':'M')+(i/(a.length-1)*72).toFixed(1)+' '+(26-(p.v-lo)/(hi-lo||1)*24).toFixed(1);}).join(' ');return '<svg viewBox="0 0 72 28" aria-hidden="true"><path d="'+d+'" stroke="var(--accent)" fill="none" stroke-width="2"/></svg>';}
 $('[data-panel=watch] form',hub).onsubmit=async function(e){e.preventDefault();var input=this.elements.ticker,t=input.value.trim().toUpperCase(),list=read('mk_my_tickers_'+market,[]);if(!RE.test(t)){message('티커 형식을 확인하세요.');return;}if(list.includes(t))return;if(list.length>=20){message('관심종목은 최대 20개까지 저장할 수 있습니다.');return;}try{await quote(t);list.push(t);save('mk_my_tickers_'+market,list);input.value='';message('추가했습니다.');watch();}catch(e){message('시세를 찾지 못했습니다. 티커를 확인하세요.');}};
 hub.addEventListener('click',function(e){var b=e.target.closest('[data-remove-watch]');if(b){save('mk_my_tickers_'+market,read('mk_my_tickers_'+market,[]).filter(function(t){return t!==b.dataset.removeWatch;}));watch();}b=e.target.closest('[data-remove-hold]');if(b){var h=read('mk_hold_'+market,{});delete h[b.dataset.removeHold];save('mk_hold_'+market,h);account();}b=e.target.closest('[data-edit-hold]');if(b){var h=read('mk_hold_'+market,{})[b.dataset.editHold],f=$('[data-panel=account] form',hub);f.elements.ticker.value=b.dataset.editHold;f.elements.quantity.value=h.q;f.elements.cost.value=h.c||0;f.elements.ticker.focus();}});
 $('[data-panel=account] form',hub).onsubmit=async function(e){e.preventDefault();var t=this.elements.ticker.value.trim().toUpperCase(),q=+this.elements.quantity.value,c=+this.elements.cost.value;if(!RE.test(t)||!(q>0)||!Number.isFinite(q)||!(c>=0)||!Number.isFinite(c)){message('티커·수량·평균단가를 확인하세요.');return;}var h=read('mk_hold_'+market,{});if(Object.keys(h).length>=30&&!h[t]){message('계좌는 최대 30종목까지 입력할 수 있습니다.');return;}try{await quote(t);h[t]={q:q,c:c||null};save('mk_hold_'+market,h);this.reset();message('계좌 정보를 저장했습니다.');account();}catch(e){message('시세를 확인할 수 없어 저장하지 않았습니다.');}};
 var keep=$('.ut-save input',hub);keep.checked=localStorage.getItem('stock_account_persist_'+market)==='1';keep.onchange=function(){var h=read('mk_hold_'+market,{});localStorage.setItem('stock_account_persist_'+market,keep.checked?'1':'0');localStorage.removeItem('mk_hold_'+market);sessionStorage.removeItem('mk_hold_'+market);save('mk_hold_'+market,h);};
 var accountSeq=0;
 async function account(){var seq=++accountSeq,h=read('mk_hold_'+market,{}),keys=Object.keys(h),box=$('.ut-account',hub);if(!keys.length){box.textContent='보유 종목을 입력하면 평가금액·손익·비중을 계산합니다.';return;}box.textContent='계좌 시세를 불러오는 중…';var rows=await Promise.all(keys.map(async function(t){try{var r=await quote(t);return Object.assign({},r,{q:h[t].q,c:h[t].c,total:r.px*h[t].q,profit:h[t].c==null?null:(r.px-h[t].c)*h[t].q});}catch(e){return{t:t,q:h[t].q,c:h[t].c};}}));if(seq!==accountSeq)return;var totals={};rows.forEach(function(r){if(r.currency)totals[r.currency]=(totals[r.currency]||0)+r.total;});box.innerHTML='<div class="ut-totals">'+Object.keys(totals).map(function(c){return'<b>'+c+' 평가금액 '+money(totals[c],c)+'</b>';}).join('')+'</div><table><thead><tr><th>종목</th><th>수량</th><th>평균단가</th><th>현재가</th><th>평가금액</th><th>손익</th><th>등락률</th><th>비중</th><th>관리</th></tr></thead><tbody>'+rows.map(function(r){return '<tr>'+[r.t,String(r.q),money(r.c,r.currency),money(r.px,r.currency),money(r.total,r.currency),money(r.profit,r.currency),pct(r.pct),r.currency?pct(100*r.total/totals[r.currency]):'—'].map(function(s,i){return'<td data-label="'+['종목','수량','평균단가','현재가','평가금액','손익','등락률','비중'][i]+'">'+esc(s)+'</td>';}).join('')+'<td><button type="button" data-edit-hold="'+esc(r.t)+'">수정</button><button type="button" data-remove-hold="'+esc(r.t)+'">삭제</button></td></tr>';}).join('')+'</tbody></table>'+(rows.some(function(r){return!r.currency;})?'<p>일부 시세를 불러오지 못했습니다. 해당 종목은 합계에서 제외됩니다.</p>':'');}
 function cutoff(end,months){var d=new Date(end),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-months);d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));return +d;}
 function draw(box,series,note){if(!series.length){box.textContent='공통 시세 구간이 부족합니다.';return;}var lo=Math.min(0,...series.flatMap(function(s){return s.y;})),hi=Math.max(0,...series.flatMap(function(s){return s.y;}));if(lo===hi){lo-=1;hi+=1;}var W=760,H=300,L=65,R=20,T=24,D=50,pw=W-L-R,ph=H-T-D,colors=['#16865c','#4386db','#d5872a','#835ad8'],start=Math.min(...series.map(function(s){return s.ts[0];})),end=Math.max(...series.map(function(s){return s.ts[s.ts.length-1];})),x=function(t){return L+(t-start)/(end-start||1)*pw;},y=function(v){return T+(hi-v)/(hi-lo)*ph;},grid='';for(var i=0;i<5;i++){var v=lo+(hi-lo)*i/4;grid+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y(v)+'" y2="'+y(v)+'" stroke="currentColor" opacity=".12"/><text x="'+(L-8)+'" y="'+(y(v)+4)+'" text-anchor="end">'+v.toFixed(1)+'%</text>';}[start,(start+end)/2,end].forEach(function(t){grid+='<text x="'+x(t)+'" y="'+(H-24)+'" text-anchor="middle">'+new Date(t).toISOString().slice(0,10)+'</text>';});box.innerHTML='<div class="ut-legend">'+series.map(function(s,i){return'<b style="color:'+colors[i%colors.length]+'">'+esc(s.name)+' '+pct(s.y[s.y.length-1])+'</b>';}).join('')+'</div><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="수익률 비교. 세로축 수익률 퍼센트, 가로축 날짜"><g fill="currentColor" font-size="11">'+grid+'<text x="'+L+'" y="14">수익률(%)</text><text x="380" y="296" text-anchor="middle">날짜</text></g>'+series.map(function(s,i){return'<path fill="none" stroke="'+colors[i%colors.length]+'" stroke-width="2" '+(s.benchmark?'stroke-dasharray="6 3"':'')+'d="'+s.y.map(function(v,j){return(j?'L':'M')+x(s.ts[j]).toFixed(1)+' '+y(v).toFixed(1);}).join(' ')+'"/>';}).join('')+'</svg><p>'+esc(note)+'</p>';}
 $('[data-panel=compare] form',hub).onsubmit=async function(e){e.preventDefault();var ts=this.elements.symbols.value.toUpperCase().split(/[ ,]+/).filter(Boolean),months=+this.elements.months.value,box=$('.ut-compare-chart',hub);if(ts.length>3||!ts.length||ts.some(function(t){return!RE.test(t);})){message('올바른 티커를 최대 3개 입력하세요.');return;}box.textContent='수익률을 불러오는 중…';try{var data=await Promise.all(ts.map(function(t){return quote(t,'10y');})),end=Math.min(...data.map(function(r){return r.points[r.points.length-1].t;})),start=cutoff(end,months);var series=data.map(function(r){var a=r.points.filter(function(p){return p.t>=start&&p.t<=end;});if(a.length<2)throw Error('기간 부족');return{name:r.name||krNames[r.t]||'종목명 미수신',ts:a.map(function(p){return p.t;}),y:a.map(function(p){return 100*(p.v/a[0].v-1);})};});draw(box,series,'가격 수익률 · 배당·세금·환율 제외 · 시세가 제공되는 실제 기간만 표시합니다.');}catch(e){box.textContent='선택한 종목의 수익률을 불러오지 못했습니다.';}};
 $('.ut-account-curve',hub).onclick=async function(){var h=read('mk_hold_'+market,{}),keys=Object.keys(h),box=$('.ut-account-chart',hub),months=+$('.ut-account-period',hub).value;if(!keys.length){box.textContent='보유 종목을 먼저 입력하세요.';return;}box.textContent='계좌 곡선을 불러오는 중…';try{var data=await Promise.all(keys.map(function(t){return quote(t,'10y');})),currencies=Array.from(new Set(data.map(function(r){return r.currency;})));if(currencies.length!==1){box.textContent='계좌 곡선은 동일 통화 종목만 계산할 수 있습니다. 여러 통화의 금액을 임의로 합산하지 않습니다.';return;}var end=Math.min(...data.map(function(r){return r.points[r.points.length-1].t;})),start=cutoff(end,months),maps=data.map(function(r){return new Map(r.points.map(function(p){return[p.d,p];}));}),common=data[0].points.filter(function(p){return p.t>=start&&p.t<=end&&maps.every(function(m){return m.has(p.d);});});if(common.length<2)throw Error('공통 날짜 부족');var values=common.map(function(p){return data.reduce(function(sum,r,i){return sum+maps[i].get(p.d).v*h[r.t].q;},0);}),series=[{name:'내계좌 '+currencies[0],ts:common.map(function(p){return p.t;}),y:values.map(function(v){return100(v/values[0]-1);})}];var bm=market==='crypto'?'BTC-USD':currencies[0]==='KRW'?'^KS11':'QQQ';try{var bench=await quote(bm,'10y'),map=new Map(bench.points.map(function(p){return[p.d,p];})),points=common.filter(function(p){return map.has(p.d);});if(points.length>1){var base=map.get(points[0].d).v,valueMap=new Map(common.map(function(p,i){return[p.d,values[i]];})),accountBase=valueMap.get(points[0].d);series[0]={name:series[0].name,ts:points.map(function(p){return p.t;}),y:points.map(function(p){return100(valueMap.get(p.d)/accountBase-1);})};series.push({name:bm+' 벤치마크',benchmark:true,ts:points.map(function(p){return p.t;}),y:points.map(function(p){return100(map.get(p.d).v/base-1);})});}}catch(e){}draw(box,series,'현재 수량을 과거에도 동일하게 보유한 가격 수익률 시뮬레이션입니다. 실제 거래·입출금·배당·환율은 반영하지 않습니다.');}catch(e){box.textContent='일부 종목의 시세가 없어 계좌 곡선을 계산할 수 없습니다.';}};
 function return100(n){return n*100;}
 window.MK_MY_ADD=async function(t){t=String(t).trim().toUpperCase();if(!RE.test(t))return false;var list=read('mk_my_tickers_'+market,[]);if(list.includes(t))return true;if(list.length>=20)return false;try{await quote(t);list.push(t);save('mk_my_tickers_'+market,list);watch();return true;}catch(e){return false;}};
 function investment(){permit(function(){hub.open=true;hub.scrollIntoView({behavior:'smooth',block:'start'});watch();});}
 var toc=$('#pro-toc');if(toc){var btn=document.createElement('button');btn.type='button';btn.className='unified-invest-link';btn.textContent='내 투자';btn.onclick=investment;toc.appendChild(btn);}document.addEventListener('click',function(e){var b=e.target.closest('#mk-tabbar button');if(b&&/내 투자|내투자/.test(b.textContent)){e.preventDefault();e.stopImmediatePropagation();investment();}},true);
 hub.addEventListener('toggle',function(){if(hub.open)watch();});window.addEventListener('storage',function(){if(hub.open){watch();account();}});
 hub.querySelector('summary').textContent='내 투자 도구';
 var inner=document.createElement('section');inner.className='stock-tools-hub crypto-tools-hub';var heading=document.createElement('div');heading.className='stock-tools-heading';heading.innerHTML='<h2>🪙 가상화폐 투자 도구</h2><span>저장 정보는 이 브라우저에서 관리</span>';inner.append(heading);Array.from(hub.children).forEach(function(n){if(n.tagName!=='SUMMARY')inner.append(n);});hub.append(inner);
 hub.querySelector('nav').classList.add('stock-tools-links');hub.querySelector('[data-tool=watch]').textContent='관심종목';hub.querySelector('[data-tool=account]').textContent='내 계좌';hub.querySelector('[data-tool=compare]').textContent='종목 비교';hub.querySelector('.ut-hint').innerHTML='한글 종목명 또는 종목 코드로 검색하세요. 예: 비트코인 · BTC-USD<br>관심종목·계좌는 가상화폐 전용으로 저장됩니다.';
 hub.querySelectorAll('form').forEach(function(form,i){var input=form.elements.ticker||form.elements.symbols,original=form.onsubmit;if(!input||!original)return;input.maxLength=100;input.placeholder=form.elements.symbols?'비트코인, 이더리움 (쉼표로 구분)':'비트코인 또는 BTC-USD';input.setAttribute('aria-label',form.elements.symbols?'비교 종목명 또는 티커 · 쉼표로 구분':'종목명 또는 티커');var label=input.parentElement;if(label.firstChild&&label.firstChild.nodeType===3)label.firstChild.textContent=form.elements.symbols?'비교 종목 · 최대 3개':'종목명 또는 티커';var dl=document.createElement('datalist');dl.id='kr-symbol-options-'+i;input.setAttribute('list',dl.id);input.after(dl);var debounce,seq=0;input.addEventListener('input',function(e){if(e.isComposing)return;clearTimeout(debounce);var request=++seq;debounce=setTimeout(async function(){var q=input.value.split(',').pop().trim();if(q.length<2)return;try{var rows=await candidates(q);if(request!==seq)return;dl.replaceChildren();rows.slice(0,20).forEach(function(r){var option=document.createElement('option');option.value=form.elements.symbols?(input.value.includes(',')?input.value.slice(0,input.value.lastIndexOf(',')+1)+' ':'')+r.symbol:r.symbol;option.label=r.name+' · '+r.symbol;dl.append(option);});}catch(e){message('검색 연결을 확인해 주세요. 종목 코드를 직접 입력할 수도 있습니다.');}},350);});input.addEventListener('compositionend',function(){input.dispatchEvent(new Event('input',{bubbles:true}));});
 form.onsubmit=async function(e){e.preventDefault();var button=form.querySelector('button[type=submit],button:not([type])');if(button&&button.disabled)return;if(button)button.disabled=true;try{if(form.elements.symbols){var values=input.value.split(/[,，;\n]+/).map(function(x){return x.trim();}).filter(Boolean);if(!values.length||values.length>3)throw Error('종목을 쉼표로 구분하여 최대 3개 입력해 주세요.');input.value=(await Promise.all(values.map(resolveSymbol))).join(', ');}else input.value=await resolveSymbol(input.value);await original.call(form,e);}catch(error){message(error.message||'종목 검색에 실패했습니다.');}finally{if(button)button.disabled=false;}};
 });

 var compareForm=hub.querySelector('[data-panel=compare] form'),canonical=compareForm.elements.symbols,previousSubmit=compareForm.onsubmit;
 canonical.type='hidden';canonical.required=false;canonical.parentElement.hidden=true;
 var inputs=document.createElement('div');inputs.className='crypto-compare-inputs';
 [1,2,3].forEach(function(index){var label=document.createElement('label');label.textContent='종목 '+index+(index===1?' · 필수':'');var field=document.createElement('input');field.name='compare'+index;field.placeholder=['비트코인','이더리움','솔라나'][index-1];field.required=index===1;field.maxLength=40;field.setAttribute('aria-label','비교 종목 '+index+' · 한글명 또는 코드');var dl=document.createElement('datalist');dl.id='kr-compare-options-'+index;field.setAttribute('list',dl.id);label.append(field,dl);inputs.append(label);var timer,sequence=0;field.addEventListener('input',function(e){if(e.isComposing)return;clearTimeout(timer);var seq=++sequence;timer=setTimeout(async function(){if(field.value.trim().length<2)return;try{var rows=await candidates(field.value.trim());if(seq!==sequence)return;dl.replaceChildren();rows.slice(0,20).forEach(function(row){var option=document.createElement('option');option.value=row.symbol;option.label=row.name;dl.append(option);});}catch(e){message('검색 연결을 확인해 주세요.');}},350);});field.addEventListener('compositionend',function(){field.dispatchEvent(new Event('input',{bubbles:true}));});});
 compareForm.prepend(inputs);compareForm.onsubmit=async function(e){e.preventDefault();var values=[1,2,3].map(function(i){return compareForm.elements['compare'+i].value.trim();}).filter(Boolean);if(!values.length){message('비교할 종목을 입력해 주세요.');return;}canonical.value=values.join(', ');return previousSubmit.call(compareForm,e);};

})();