(function(){
 'use strict';
 function ready(){
 var page=location.pathname.split('/').pop().replace('.html',''),other=/^(bond|crypto|finprod|ipo|p2p|fx|trade)$/.test(page);if(!other&&page!=='stock'&&page!=='kr-stock')return;document.body.classList.add('refine-v92','v92-'+page);if(other)document.body.classList.add('v92-other');
 function admin(){try{return localStorage.getItem('mk_gate_off')==='1';}catch(e){return false;}}
 function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
 function chart(box,values,labels,note){if(!box)return;var points=values.map(function(v,i){return {v:v===null||v===undefined||v===''?NaN:Number(v),label:labels&&labels[i]||String(i+1)};}).filter(function(p){return Number.isFinite(p.v)&&p.v>=0&&p.v<=100;});if(points.length<2){box.innerHTML='<p class="v92-trend-empty">'+esc(note||'기간 내 점수 기록이 부족합니다.')+'</p>';if(points.length)box.innerHTML+='<b class="v92-current">현재 '+points[0].v.toFixed(1)+'점</b>';return;}
 var W=320,H=180,L=28,R=12,T=16,B=28,x=function(i){return L+i*(W-L-R)/(points.length-1);},y=function(v){return T+(100-v)*(H-T-B)/100;},d=points.map(function(p,i){return(i?'L':'M')+x(i).toFixed(1)+' '+y(p.v).toFixed(1);}).join(' '),last=points[points.length-1];box.innerHTML='<svg viewBox="0 0 320 180" role="img" aria-label="최근 공포탐욕 흐름 · 0~100점"><g fill="var(--tx2)" font-size="10">'+[0,50,100].map(function(v){return '<path d="M28 '+y(v)+'H308" fill="none" stroke="var(--line)"/><text x="23" y="'+(y(v)+3)+'" text-anchor="end">'+v+'</text>';}).join('')+'<text x="28" y="175">'+esc(points[0].label)+'</text><text x="308" y="175" text-anchor="end">'+esc(last.label)+'</text></g><path d="'+d+'" fill="none" stroke="var(--accent)" stroke-width="2.5"/><circle cx="308" cy="'+y(last.v)+'" r="4" fill="var(--accent)"/></svg><div class="stock-trend-labels"><span>'+esc(note||'선택 기간의 실제 점수')+'</span><b>최근 '+last.v.toFixed(1)+'점</b></div>';}
 if(page==='stock'&&typeof window.bars==='function'){var originalBars=window.bars;window.bars=function(pre,arr,labels){var result=originalBars.apply(this,arguments);if(pre==='us')chart(document.getElementById('us-trend'),arr,labels,'선택 기간');return result;};}
 if(page==='kr-stock'){
 var card=document.getElementById('kr-card'),gauge=card&&card.querySelector('.stock-gauge');if(card&&gauge){var heading=document.createElement('div');heading.className='v92-fg-header';var h=card.querySelector('h3');heading.append(h);var tabs=document.createElement('div');tabs.className='tabs v92-kr-periods';tabs.setAttribute('aria-label','공포탐욕 기록 기간');var selected=1;[['1일',1],['1주',7],['1개월',30],['1년',365]].forEach(function(s){var b=document.createElement('button');b.type='button';b.textContent=s[0];b.dataset.days=s[1];b.setAttribute('aria-pressed',String(s[1]===1));if(s[1]===1)b.className='on';tabs.append(b);});heading.append(tabs);card.prepend(heading);
 var row=document.createElement('div');row.className='v92-fg-top';gauge.before(row);var oldParent=gauge.parentElement;row.append(gauge);var area=document.createElement('div');area.className='v92-trend-area';area.innerHTML='<div class="mut v92-trend-title">최근 흐름</div><div id="kr-trend" class="trend-lg"></div>';row.append(area);var sourceLine=card.querySelector('.fg-src');if(sourceLine)sourceLine.after(row);else heading.after(row);if(oldParent!==card&&oldParent!==row)oldParent.style.display='none';var krHistory=[];try{krHistory=JSON.parse(localStorage.getItem('mk_kr_fg_received_v92')||'[]');if(!Array.isArray(krHistory))krHistory=[];krHistory=krHistory.filter(function(p){return p&&Number.isFinite(p.t)&&Number.isFinite(p.v)&&p.v>=0&&p.v<=100;});}catch(e){}
 function render(){var start=Date.now()-selected*86400000,rows=krHistory.filter(function(p){return Number.isFinite(p.t)&&Number.isFinite(p.v)&&p.t>=start&&p.v>=0&&p.v<=100;});chart(document.getElementById('kr-trend'),rows.map(function(p){return p.v;}),rows.map(function(p){return new Date(p.t).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric'});}),rows.length<2?'수신 기록이 쌓이면 기간별 흐름을 표시합니다.':'수신 기록 기준');}
 function capture(){var source=document.getElementById('kr-val'),state=document.getElementById('kr-state'),raw=source&&source.textContent.trim(),n=Number(raw);if(!raw||!Number.isFinite(n)||n<0||n>100||/실패|불러|연동/.test(state&&state.textContent||'')){render();return;}var now=Date.now(),day=new Date(now).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),last=krHistory[krHistory.length-1];if(last&&last.day===day){last.v=n;last.t=now;}else krHistory.push({t:now,v:n,day:day});krHistory=krHistory.filter(function(p){return p.t>now-370*86400000;}).slice(-370);try{localStorage.setItem('mk_kr_fg_received_v92',JSON.stringify(krHistory));}catch(e){}render();}
 tabs.addEventListener('click',function(e){var b=e.target.closest('[data-days]');if(!b)return;selected=Number(b.dataset.days);tabs.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b);x.setAttribute('aria-pressed',String(x===b));});render();});capture();new MutationObserver(capture).observe(document.getElementById('kr-val'),{childList:true,subtree:true});
 }
 }
 if(page==='crypto'){
 var global=document.getElementById('cry-global-trend'),c=global&&global.closest('.card');if(c){c.classList.add('v92-global-trend');var h=c.querySelector('.market-fold-h'),body=c.querySelector('.market-fold-body');if(h&&body){var fresh=h.cloneNode(true);h.replaceWith(fresh);fresh._set=function(open){fresh.classList.toggle('open',open);body.hidden=!open;var button=fresh.querySelector('.market-fold-btn');if(button){button.textContent=open?'접기 −':'펼치기 ＋';button.setAttribute('aria-expanded',String(open));}};fresh.addEventListener('click',function(e){e.preventDefault();var open=body.hidden;if(open&&window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(function(){fresh._set(true);});else fresh._set(open);});fresh._set(true);}c.classList.add('cross-open','m-open');}
 var dial=document.getElementById('cf-dial'),cc=dial&&dial.closest('.card');if(cc){cc.classList.add('v92-crypto-gauge');var title=cc.querySelector('.fg-hd h3');if(title)Array.from(title.childNodes).forEach(function(n){if(n.nodeType===3)n.textContent='공포탐욕지수 ';});cc.querySelectorAll('.tabs[data-group=cf] button').forEach(function(b,i){b.textContent=['1일','1주','1개월','1년'][i];});}
 }
 function repair(){
  if(other){var nav=document.getElementById('pro-toc');if(nav)nav.remove();var head=document.querySelector('.v86-page-head'),actions=document.querySelector('.v90-actions');if(head&&actions&&actions.parentElement!==head){head.classList.add('v92-page-head');head.append(actions);}}
  if(page==='kr-stock')document.querySelectorAll('[id^="fin-"],[id^="lev-hold-"]').forEach(function(panel){panel.classList.add('v92-detail-panel');panel.querySelectorAll('table').forEach(function(t){if(!t.closest('.scroll')){var wrap=document.createElement('div');wrap.className='scroll v92-detail-scroll';wrap.tabIndex=0;t.before(wrap);wrap.append(t);}var columns=t.querySelectorAll('thead tr:last-child th').length;t.classList.toggle('v92-wide-detail',columns>=5);});});
 }
 repair();var pending;new MutationObserver(function(records){if(records.every(function(r){return r.target.closest&&r.target.closest('#v92-update-history,#v92-usage,#kr-trend');}))return;if(pending)return;pending=setTimeout(function(){pending=null;repair();},180);}).observe(document.querySelector('main'),{childList:true,subtree:true});
 var footer=document.querySelector('footer');if(!footer)return;
 var history=document.createElement('details');history.id='v92-update-history';history.hidden=true;var summary=document.createElement('summary');summary.textContent='업데이트 이력 · 일자·페이지·기능';history.append(summary);
 var records=[['2026-10-11','v92','미국주식','공포탐욕 최근 흐름·여백, 하단 사용량, 통합 이력'],['2026-10-11','v92','한국주식','기간 탭·수신 점수 흐름, 투자자/자금 표 상단 정렬, 상세 표·링크 간격'],['2026-10-11','v92','가상화폐','현재 지수 제목, 글로벌 트렌드 기본 펼침·정렬, 제목 외곽선 효과 제거'],['2026-10-11','v92','채권·가상화폐·금융상품·공모주·P2P·환율·매매김군','상단 별도 탭줄 제거, 제목 옆 화면 관리 버튼'],['2026-10-11','v91','한국주식','한글 종목명 검색·투자도구·종목 타일·Help'],['2026-10-11','v90','기타 8개 페이지','표·카드·버튼·모바일 간격 통일'],['2026-10-11','v89','한국주식','7개 세부지표·상태·접기 동작 정리']];
 var legacy=document.getElementById('stock-update-history');if(legacy)legacy.querySelectorAll('li').forEach(function(li){records.push(['2026-10-10','기존','미국주식',li.textContent.replace(/^2026\.10\.10\s*·\s*/, '')]);});
 var dates=Array.from(new Set(records.map(function(r){return r[0];}))).sort().reverse();dates.forEach(function(date){var group=document.createElement('details');group.className='v92-update-date';var s=document.createElement('summary');s.textContent=date;group.append(s);var table=document.createElement('table');table.innerHTML='<thead><tr><th>버전</th><th>페이지</th><th>개선 기능</th></tr></thead><tbody>'+records.filter(function(r){return r[0]===date;}).map(function(r){return '<tr><td data-label="버전">'+esc(r[1])+'</td><td data-label="페이지">'+esc(r[2])+'</td><td data-label="개선 기능">'+esc(r[3])+'</td></tr>';}).join('')+'</tbody>';group.append(table);history.append(group);});footer.append(history);
 footer.addEventListener('click',function(e){if(!e.target.closest('.cross-update,#stock-update-footer,#stamp-top'))return;if(e.target.closest('#v92-update-history'))return;if(!admin())return;e.preventDefault();e.stopImmediatePropagation();history.open=!history.open;},true);
 var usage;
 if(page==='stock'){usage=document.createElement('details');usage.id='v92-usage';usage.hidden=true;usage.innerHTML='<summary>📊 사용량 보기</summary><form><label>통계 키 <input type="password" autocomplete="off" required aria-label="Worker 통계 키"></label><button>조회</button></form><div class="v92-usage-result" role="status"></div>';footer.append(usage);usage.addEventListener('toggle',function(){if(!usage.open||!admin())return;var input=usage.querySelector('input');if(!input.value)try{input.value=localStorage.getItem('mk_stats_key')||'';}catch(e){}});usage.querySelector('form').onsubmit=async function(e){e.preventDefault();if(!admin())return;var result=usage.querySelector('.v92-usage-result'),button=this.querySelector('button'),key=this.querySelector('input').value.trim();if(!key)return;button.disabled=true;result.textContent='사용량을 불러오는 중…';try{var responses=await Promise.all([fetch('https://ai.coolzet.workers.dev/health',{cache:'no-store',signal:AbortSignal.timeout(12000)}),fetch('https://ai.coolzet.workers.dev/ev-stats?days=7&key='+encodeURIComponent(key),{cache:'no-store',signal:AbortSignal.timeout(12000)})]);if(responses.some(function(r){return!r.ok;}))throw Error(responses.some(function(r){return r.status===403;})?'통계 키를 확인해 주세요.':'사용량 연결을 확인해 주세요.');var data=await Promise.all(responses.map(function(r){return r.json();})),health=data[0],stats=data[1],metric=function(n){return Number.isFinite(n)?String(n):'—';};result.innerHTML='<p>Worker 요청 '+metric(health.total)+' · 오류(5xx) '+metric(health.err5xx)+' · 속도 제한 '+metric(health.limited)+'</p><ul>'+Object.keys(stats).sort().reverse().map(function(day){return '<li>'+esc(day)+' · 방문 '+metric(stats[day]&&stats[day].v)+'회</li>';}).join('')+'</ul><p class="mut">Worker 재시작 이후 요청 및 최근 7일 방문 집계입니다. 요금·전체 한도 사용률은 제공하지 않습니다.</p>';}catch(error){result.textContent=error.message||'사용량을 불러오지 못했습니다.';}finally{button.disabled=false;}};}
 function syncAdmin(){history.hidden=!admin();if(history.hidden)history.open=false;if(usage){usage.hidden=!admin();if(usage.hidden)usage.open=false;}}
 syncAdmin();setInterval(syncAdmin,1500);window.addEventListener('storage',syncAdmin);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
