(function(){
 'use strict';
 var B=document.body;B.classList.add('cross-v83','market-v84');var page=location.pathname.split('/').pop().replace('.html','');B.dataset.marketPage=page;
 var $=function(s,r){return(r||document).querySelector(s);},$$=function(s,r){return Array.from((r||document).querySelectorAll(s));};
 var states=[],main=$('main');if(!main)return;
 function permit(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function addFold(h,nodes){
  if(!nodes.length||h.dataset.marketFold)return;h.dataset.marketFold='1';var title=h.textContent.replace(/\s+/g,' ').trim(),box=document.createElement('div');box.className='market-fold-body';h.after(box);nodes.forEach(function(n){box.appendChild(n);});h.classList.add('market-fold-h');
  var label=document.createElement('span');while(h.firstChild)label.appendChild(h.firstChild);label.className='market-fold-title';h.appendChild(label);
  var btn=document.createElement('button');btn.type='button';btn.className='market-fold-btn';btn.setAttribute('aria-label',title+' 펼치기/접기');h.appendChild(btn);box.id='market-panel-'+states.length;btn.setAttribute('aria-controls',box.id);
  function set(on){box.hidden=!on;h.classList.toggle('market-open',on);btn.textContent=on?'접기 −':'펼치기 +';btn.setAttribute('aria-expanded',String(on));}
  set(false);h.addEventListener('click',function(e){if(e.target.closest('a'))return;if(box.hidden)permit(function(){set(true);});else set(false);});h._set=function(on){if(on)permit(function(){set(true);});else set(false);};states.push({h:h,set:set,title:title});
 }
 // Fold section blocks, leaving the page title and live market overview visible.
 $$('main h2').filter(function(h){return !h.classList.contains('pg-title')&&!h.closest('.card,.scard,.p2p-hero')&&h.parentElement.classList.contains('wrap');}).forEach(function(h){var a=[],n=h.nextElementSibling;while(n&&n.tagName!=='H2'){a.push(n);n=n.nextElementSibling;}addFold(h,a);});
 // Product cards retain their existing node identities, tabs, forms and listeners.
 $$('main .card>h3,main .card>.fg-hd>h3').forEach(function(h){var card=h.closest('.card');if(card.closest('.market-fold-body')||card.querySelector('canvas,.dial'))return;var anchor=h.parentElement.classList.contains('fg-hd')?h.parentElement:h,nodes=[],n=anchor.nextElementSibling;while(n){nodes.push(n);n=n.nextElementSibling;}if(anchor!==h){var holder=document.createElement('div');holder.className='market-card-header';h.before(holder);holder.appendChild(h);Array.from(anchor.children).filter(function(x){return x!==holder;}).forEach(function(x){holder.appendChild(x);});addFold(h,nodes);}else addFold(h,nodes);});
 $$('main .wrap>h3').forEach(function(h){if(h.closest('.market-fold-body'))return;var a=[],n=h.nextElementSibling;while(n&&n.tagName!=='H2'&&n.tagName!=='H3'){a.push(n);n=n.nextElementSibling;}addFold(h,a);});
 // Trading strategy toggles are owned by the original trading engine.
 $$('[data-sc]',main).forEach(function(btn){var card=document.getElementById(btn.dataset.sc);if(!card)return;card.classList.remove('open');btn.classList.add('market-fold-btn');btn.setAttribute('aria-label',(card.querySelector('.ti')||card).textContent.trim()+' 펼치기/접기');function sync(){var on=card.classList.contains('open');btn.textContent=on?'접기 −':'펼치기 +';btn.setAttribute('aria-expanded',String(on));}sync();new MutationObserver(sync).observe(card,{attributes:true,attributeFilter:['class']});states.push({h:card.querySelector('.scard-h'),title:(card.querySelector('.ti')||card).textContent.trim(),set:function(on){if(card.classList.contains('open')!==on)btn.click();}});});
 $$('details',main).forEach(function(d){d.open=false;});
 var status=$('#pro-status'),bar=document.createElement('div');bar.className='cross-status-actions market-actions';
 var retry=$('#ps-rf');if(retry)bar.appendChild(retry);
 [['0','모두 접기','⊟'],['1','모두 펼치기','⊞']].forEach(function(x){var b=document.createElement('button');b.type='button';b.dataset.mobileIcon=x[2];b.setAttribute('aria-label',x[1]);b.title=x[1];var label=document.createElement('span');label.className='cross-action-label';label.textContent=x[1];b.appendChild(label);bar.appendChild(b);b.onclick=function(){var on=x[0]==='1',run=function(){states.forEach(function(s){s.set(on);});$$('details',main).forEach(function(d){d.open=on;});};if(on)permit(run);else run();};});
 if(retry){retry.setAttribute('aria-label','다시 불러오기');retry.title='다시 불러오기';retry.dataset.mobileIcon='↻';retry.innerHTML='<span class="cross-action-label">↻ 다시 불러오기</span>';}
 if(status)status.appendChild(bar);else main.prepend(bar);
 // Navigation uses current section headings; opening a section precedes scrolling.
 var toc=$('#pro-toc');if(!toc&&states.length){toc=document.createElement('nav');toc.id='pro-toc';toc.setAttribute('aria-label','페이지 바로가기');(status||$('header')).after(toc);}
 if(toc){toc.innerHTML='';var navItems=$$('main h2').map(function(h){return states.find(function(s){return s.h===h;})||{h:h,title:h.textContent.replace(/\s+/g,' ').trim(),set:function(){}};});states.forEach(function(s){if(!navItems.some(function(x){return x.h===s.h;}))navItems.push(s);});navItems.forEach(function(s,i){var a=document.createElement('a');a.href='#market-heading-'+i;s.h.id=s.h.id||'market-heading-'+i;a.href='#'+s.h.id;a.textContent=s.title.slice(0,18);a.title=s.title;toc.appendChild(a);a.onclick=function(e){e.preventDefault();e.stopPropagation();permit(function(){s.set(true);s.h.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});});};});}
 // Existing quick navigation items may point inside a newly collapsed group.
 document.addEventListener('click',function(e){var link=e.target.closest('a[href^="#"]');if(!link)return;var id=link.getAttribute('href').slice(1),target=id&&document.getElementById(id);if(!target)return;var closed=[];var node=target.parentElement;while(node){if(node.classList.contains('market-fold-body')&&node.hidden){var state=states.find(function(s){return s.h.nextElementSibling===node;});if(state)closed.unshift(state);}node=node.parentElement;}if(closed.length){e.preventDefault();permit(function(){closed.forEach(function(s){s.set(true);});target.scrollIntoView({behavior:'smooth',block:'start'});});}},true);
 var help=document.createElement('details');help.className='market-help';help.innerHTML='<summary>ⓘ 지표 읽는 법 · Help</summary><p><b>가격·환율</b>은 최근 수신 시세입니다. 시장 휴장이나 제공처 지연 시에는 최신 거래 시각을 확인하세요.</p><p><b>등락률</b>은 선택 기간의 기준 가격 대비 변화입니다. 상품 금리·수익률·수수료는 서로 다른 수치이므로 표의 단위를 확인하세요.</p><p><b>수익률 곡선</b>은 가격 흐름을 비교합니다. 배당·세금·수수료를 포함하는지는 해당 그래프의 설명을 확인하세요.</p><p><b>공모주·금융상품·P2P 일정</b>은 실제 신청 전 제공기관의 조건과 모집 상태를 확인하세요.</p>';main.appendChild(help);
 // Uniform quote and spark layout applies to asynchronously generated rows too.
 function tables(){ $$('table',main).forEach(function(t){if(t.dataset.marketTable)return;t.dataset.marketTable='1';if(!t.closest('.scroll')){var w=document.createElement('div');w.className='scroll market-scroll';t.before(w);w.appendChild(t);}var cols=$$('thead th',t);cols.forEach(function(th,i){if(/가격|현재가|종가|진입가|청산가|매수가|환율|매매기준율|금리|수익률/.test(th.textContent)){Array.from(t.rows).forEach(function(r){var c=r.cells[i];if(c)c.classList.add('market-number');});}});});}
 tables();var timer;new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(tables,200);}).observe(main,{childList:true,subtree:true});
 var up=$('#pro-top'),gift=$('#naver-gift-link');if(up){var floating=document.createElement('div');floating.className='cross-floating';if(gift){var g=document.createElement('a');g.href=gift.href;g.target='_blank';g.rel='noopener';g.className='cross-gift';g.textContent='🎁';g.setAttribute('aria-label','네이버포인트 선물하기');g.title='네이버포인트 선물하기';floating.appendChild(g);}floating.appendChild(up);B.appendChild(floating);var nav=$('#mk-tabbar');function measure(){B.style.setProperty('--cross-nav-height',nav?Math.round(nav.getBoundingClientRect().height)+'px':'0px');}measure();if(window.ResizeObserver&&nav)new ResizeObserver(measure).observe(nav);window.addEventListener('resize',measure);}
 var footer=$('footer');if(footer){var version=$('#mk-ver');if(version)version.hidden=true;var stamp=$('#stamp');if(stamp)stamp.hidden=true;var update=document.createElement('button');update.type='button';update.className='cross-update';update.textContent='업데이트 · 2026.10.11';footer.appendChild(update);function admin(){try{return localStorage.getItem('mk_gate_off')==='1';}catch(e){return false;}}function refreshAdmin(){update.disabled=!admin();}refreshAdmin();setInterval(refreshAdmin,4000);update.onclick=function(){if(!admin())return;var log=$('.cross-update-log',footer);if(!log){log=document.createElement('div');log.className='cross-update-log';log.innerHTML='<b>업데이트 이력</b><p>2026-10-11 · 공통 디자인 적용: 카드·버튼·여백, 기본 접힘·방문 중 펼침 유지, 전체 접기·펼치기, 가격 볼드·스파크라인 정렬, 모바일 조작, Help, 선물·맨 위로 위치.</p>';footer.appendChild(log);}else log.hidden=!log.hidden;};}
})();

;
(function(){
 var page=location.pathname.split('/').pop();if(!['crypto.html','fx.html','bond.html'].includes(page))return;var cfg=page==='crypto.html'?{base:'BTC-USD',name:'비트코인',list:[['ETH-USD','이더리움'],['SOL-USD','솔라나'],['XRP-USD','리플'],['BTC-USD','비트코인']]}:page==='fx.html'?{base:'KRW=X',name:'원/달러',list:[['JPYKRW=X','원/엔'],['EURKRW=X','원/유로'],['CNYKRW=X','원/위안'],['KRW=X','원/달러']]}:{base:'AGG',name:'미국 종합채권 ETF',list:[['TLT','미국 장기국채 ETF'],['IEF','미국 중기국채 ETF'],['LQD','미국 회사채 ETF'],['AGG','미국 종합채권 ETF']]};
 var root=document.querySelector('main');if(!root)return;
 var tools=document.createElement('details');tools.className='market-return-tools';tools.innerHTML='<summary>내 투자 도구 · 수익률 곡선</summary><p>기준 자산와 종목의 가격 수익률을 비교합니다. 배당·세금·환율은 포함하지 않습니다.</p><form><label>비교 자산 <select class="return-asset" aria-label="비교 자산"></select></label><label>기간 <select aria-label="수익률 기간"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button type="submit">비교하기</button></form><div class="cross-return-chart" role="status" aria-live="polite">종목과 기간을 선택해 비교하세요.</div>';
 root.appendChild(tools);var form=tools.querySelector('form'),box=tools.querySelector('.cross-return-chart'),cache={};var choices=form.querySelector('.return-asset');cfg.list.forEach(function(x){var o=document.createElement('option');o.value=x[0];o.textContent=x[1];choices.appendChild(o);});tools.querySelector('p').textContent=cfg.name+'를 기준으로 비교합니다. 가격 수익률이며 배당·세금·환율은 포함하지 않습니다.';
 function cutoff(months){var now=new Date(),year=now.getFullYear(),month=now.getMonth()-months,day=now.getDate(),d=new Date(year,month,1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d.getTime()/1000;}
 async function load(sym){if(cache[sym])return cache[sym];var job=(async function(){var j=await getJSON('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(sym)+'?range=10y&interval=1d');var r=j&&j.chart&&j.chart.result&&j.chart.result[0],c=r&&r.indicators&&r.indicators.quote&&r.indicators.quote[0].close;if(!r||!c)throw Error('시세 없음');return r.timestamp.map(function(t,i){return {t:t,v:c[i],d:new Date(t*1000).toISOString().slice(0,10)};}).filter(function(x){return Number.isFinite(x.v)&&x.v>0;});})();cache[sym]=job;try{return await job;}catch(e){delete cache[sym];throw e;}}
 var seq=0;
 form.addEventListener('submit',async function(e){e.preventDefault();var sym=choices.value;if(!cfg.list.some(function(x){return x[0]===sym;}))return;var n=++seq;box.textContent='수익률을 불러오는 중…';try{var data=await Promise.all([load(sym),load(cfg.base)]);if(n!==seq)return;var cut=cutoff(+form.querySelector('select[aria-label="수익률 기간"]').value),by=new Map(data[1].map(function(x){return[x.d,x];})),pairs=data[0].filter(function(x){return x.t>=cut&&by.has(x.d);});if(pairs.length<2)throw Error('해당 기간의 공통 거래일 부족');var baseA=pairs[0].v,baseB=by.get(pairs[0].d).v;var a=pairs.map(function(x){return(x.v/baseA-1)*100;}),b=pairs.map(function(x){return(by.get(x.d).v/baseB-1)*100;}),lo=Math.min(0,...a,...b),hi=Math.max(0,...a,...b);if(hi===lo){lo-=1;hi+=1;}var pad=(hi-lo)*.08;lo-=pad;hi+=pad;var W=760,H=310,L=62,R=20,T=20,D=56,pw=W-L-R,ph=H-T-D;var y=function(v){return T+(hi-v)/(hi-lo)*ph;},x=function(i){return L+i/(pairs.length-1)*pw;},path=function(v){return v.map(function(p,i){return(i?'L':'M')+x(i).toFixed(2)+' '+y(p).toFixed(2);}).join(' ');},ticks='';for(var i=0;i<5;i++){var v=lo+(hi-lo)*i/4,yy=y(v);ticks+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+yy+'" y2="'+yy+'" stroke="currentColor" opacity=".12"/><text x="'+(L-8)+'" y="'+(yy+4)+'" text-anchor="end">'+v.toFixed(1)+'%</text>';}[0,Math.floor((pairs.length-1)/2),pairs.length-1].forEach(function(i){ticks+='<text x="'+x(i)+'" y="'+(H-31)+'" text-anchor="middle">'+pairs[i].d+'</text>';});box.innerHTML='<div class="cross-return-legend"><b style="color:#16865c">● '+sym+' '+a[a.length-1].toFixed(2)+'%</b><b style="color:#4086dd">┄ '+cfg.name+' '+b[b.length-1].toFixed(2)+'%</b></div><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+sym+'와 '+cfg.name+'의 수익률 비교. 세로축 수익률 퍼센트, 가로축 날짜."><g fill="currentColor" font-size="11">'+ticks+'<text x="'+L+'" y="12">수익률(%)</text><text x="'+(W/2)+'" y="'+(H-6)+'" text-anchor="middle">날짜</text></g><path d="'+path(b)+'" fill="none" stroke="#4086dd" stroke-width="2" stroke-dasharray="6 3"/><path d="'+path(a)+'" fill="none" stroke="#16865c" stroke-width="2.5"/></svg><p>실제 공통 거래일: '+pairs[0].d+' ~ '+pairs[pairs.length-1].d+' · 상장 기간이나 공급처에 따라 선택 기간보다 짧을 수 있습니다.</p>';}catch(err){if(n===seq)box.textContent='수익률을 불러오지 못했습니다. 종목 코드와 데이터 연결을 확인해 주세요.';}});
 tools.querySelector('summary').addEventListener('click',function(e){if(tools.open)return;e.preventDefault();var fn=function(){tools.open=true;};if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();});
})();
