if(!/(^|\/)stock\.html$/.test(location.pathname)){
if(/^(mrkim-signal|kr-stock)\.html$/.test(location.pathname.split("/").pop())){
(function(){
 'use strict';
 var B=document.body,KR=B.classList.contains('kr');B.classList.add('cross-v83');
 var $=function(s,r){return(r||document).querySelector(s);},$$=function(s,r){return Array.from((r||document).querySelectorAll(s));};
 function detail(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function foldCard(card){
  if(!card)return;var h=$('h3',card);if(!h||h.dataset.crossFold)return;h.dataset.crossFold='1';var wasOpen=card.classList.contains('cross-open');card.classList.add('cross-fold','m-fold');
  var title=document.createElement('span');while(h.firstChild)title.appendChild(h.firstChild);h.appendChild(title);
  var btn=document.createElement('button');btn.type='button';btn.className='m-fold-btn';btn.setAttribute('aria-label',title.textContent+' 펼치기/접기');h.appendChild(btn);
  function set(on){card.classList.toggle('cross-open',on);card.classList.toggle('m-open',on);btn.innerHTML=on?'<em>접기</em> −':'<em>펼치기</em> +';btn.setAttribute('aria-expanded',String(on));}
  set(wasOpen);h.addEventListener('click',function(e){if(e.target.closest('a'))return;if(card.classList.contains('cross-open'))set(false);else detail(function(){set(true);});});
 }
 if(KR){
  var sub=$('#kr-sub');foldCard(sub&&sub.closest('.card'));
  var guide=$('#guide-h');if(guide&&!guide.classList.contains('fold-h')){var dl=guide.nextElementSibling;if(dl&&dl.tagName==='DL'){var help=document.createElement('button');help.type='button';help.className='cross-help';help.textContent='Help ⓘ';help.setAttribute('aria-expanded','false');guide.appendChild(help);dl.hidden=true;help.onclick=function(){dl.hidden=!dl.hidden;help.setAttribute('aria-expanded',String(!dl.hidden));};}}
  var tape=$('#pro-tick'),brief=$('#pro-brief');
  if(tape&&brief){
   var market=document.createElement('details');market.className='cross-restricted';var summary=document.createElement('summary');summary.textContent='주요 지수·환율';market.appendChild(summary);market.appendChild(tape);brief.appendChild(market);market.open=false;
   var track=document.createElement('div');track.className='cross-ticker-track';var first=document.createElement('div');first.className='cross-ticker-group';while(tape.firstChild)first.appendChild(tape.firstChild);track.appendChild(first);tape.appendChild(track);
   var second=document.createElement('div');second.className='cross-ticker-group';second.setAttribute('aria-hidden','true');second.inert=true;track.appendChild(second);
   function sync(){second.innerHTML=first.innerHTML;$$('[id]',second).forEach(function(e){e.removeAttribute('id');});}
   sync();new MutationObserver(sync).observe(first,{childList:true,subtree:true,characterData:true,attributes:true});
   summary.addEventListener('click',function(e){if(market.open)return;e.preventDefault();detail(function(){market.open=true;});});
  }
  var status=$('#pro-status'),bar=$('.fold-all');if(status){var actions=document.createElement('div');actions.className='cross-status-actions';var retry=$('#ps-rf');if(retry)actions.appendChild(retry);if(bar)actions.appendChild(bar);status.appendChild(actions);$$('button',actions).forEach(function(btn){var isRetry=btn.id==='ps-rf';btn.dataset.mobileIcon=isRetry?'↻':btn.dataset.o==='0'?'⊟':'⊞';btn.setAttribute('aria-label',isRetry?'다시 불러오기':btn.dataset.o==='0'?'모두 접기':'모두 펼치기');var span=document.createElement('span');span.className='cross-action-label';while(btn.firstChild)span.appendChild(btn.firstChild);btn.appendChild(span);});}
  var pulse=$('.pulse');if(pulse){foldCard(pulse);pulse.addEventListener('mouseenter',function(){if(matchMedia('(hover:hover)').matches)detail(function(){pulse.classList.add('cross-open','m-open');var btn=$('.m-fold-btn',pulse);if(btn){btn.innerHTML='<em>접기</em> −';btn.setAttribute('aria-expanded','true');}});});}
  new MutationObserver(function(){foldCard($('.pulse'));}).observe($('#main')||document.body,{childList:true,subtree:true});
 }else{
  var hero=$('.hero .wrap')||$('main .wrap');if(hero){
   var links=document.createElement('nav');links.className='cross-market-links';links.setAttribute('aria-label','시장 대시보드');
   [['stock.html','🇺🇸 미국주식','공포탐욕 · VIX · 핵심 종목 · 경제일정'],['kr-stock.html','🇰🇷 한국주식','코스피 · 코스닥 · 투자자 동향 · 주요 종목'],['crypto.html','₿ 가상화폐','시장 심리 · 주요 코인 · 시장 흐름']].forEach(function(x){var a=document.createElement('a');a.href=x[0];a.className='cross-market-link';var b=document.createElement('b');b.textContent=x[1];var s=document.createElement('span');s.textContent=x[2];var em=document.createElement('em');em.textContent='대시보드 열기 →';a.append(b,s,em);links.appendChild(a);});hero.appendChild(links);
   var help=document.createElement('details');help.className='cross-home-guide';help.innerHTML='<summary>ⓘ 지표 읽는 법 · Help</summary><p><b>공포탐욕지수</b>는 시장 심리를 0~100으로 나타냅니다. 낮을수록 공포, 높을수록 탐욕에 가깝습니다.</p><p><b>등락률</b>은 선택한 기간의 기준 가격 대비 변화입니다. 휴장일에는 최근 수신 시세를 확인하세요.</p><p><b>수익률 곡선</b>은 기간별 가격 흐름을 비교합니다. 과거 성과는 미래 수익을 보장하지 않습니다.</p>';hero.appendChild(help);
  }
 }
 var up=$('#pro-top'),gift=$('#naver-gift-link');if(up){var floating=document.createElement('div');floating.className='cross-floating';if(gift){var g=document.createElement('a');g.href=gift.href;g.target='_blank';g.rel='noopener';g.className='cross-gift';g.textContent='🎁';g.title='네이버포인트 선물하기';g.setAttribute('aria-label',g.title);floating.appendChild(g);}floating.appendChild(up);B.appendChild(floating);var nav=$('#mk-tabbar');function measure(){B.style.setProperty('--cross-nav-height',nav?Math.round(nav.getBoundingClientRect().height)+'px':'0px');}measure();if(window.ResizeObserver&&nav)new ResizeObserver(measure).observe(nav);window.addEventListener('resize',measure);}
 var stamp=$('#stamp');if(stamp)stamp.hidden=true;var footer=$('footer');if(footer){var version=$('#mk-ver');if(version)version.hidden=true;var updated=document.createElement('button');updated.type='button';updated.className='cross-update';updated.textContent='업데이트 · 2026.10.11';footer.appendChild(updated);function isAdmin(){try{return localStorage.getItem('mk_gate_off')==='1';}catch(e){return false;}}updated.disabled=!isAdmin();updated.addEventListener('click',function(){if(!isAdmin())return;var log=$('.cross-update-log',footer);if(!log){log=document.createElement('div');log.className='cross-update-log';log.innerHTML='<b>업데이트 이력</b><p>2026-10-11 · 미국주식 공통 디자인 적용: 카드·여백·종목 가격·스파크라인 정렬, 모바일 상태 버튼, 접기·펼치기, 지수 티커, 도움말, 선물·맨 위로 위치 통일.</p>';footer.appendChild(log);}else log.hidden=!log.hidden;});}
})();

}
;
if(/^(bond|crypto|finprod|ipo|p2p|fx|trade)\.html$/.test(location.pathname.split("/").pop())){
(function(){
 'use strict';
 var B=document.body;B.classList.add('cross-v83','market-v84');var page=location.pathname.split('/').pop().replace('.html','');B.dataset.marketPage=page;
 var $=function(s,r){return(r||document).querySelector(s);},$$=function(s,r){return Array.from((r||document).querySelectorAll(s));};
 var states=[],main=$('main');if(!main)return;$$('h2.fold-h',main).forEach(function(h){if(!h._set)return;h._set(false);states.push({h:h,title:($('.fold-t',h)||h).textContent.trim(),set:function(on){h._set(on);}});});
 function permit(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function addFold(h,nodes){
  if(!nodes.length||h.dataset.marketFold||h.classList.contains('fold-h'))return;h.dataset.marketFold='1';var title=h.textContent.replace(/\s+/g,' ').trim(),box=document.createElement('div');box.className='market-fold-body';h.after(box);nodes.forEach(function(n){box.appendChild(n);});h.classList.add('market-fold-h');
  var label=document.createElement('span');while(h.firstChild)label.appendChild(h.firstChild);label.className='market-fold-title';h.appendChild(label);
  var btn=document.createElement('button');btn.type='button';btn.className='market-fold-btn';btn.setAttribute('aria-label',title+' 펼치기/접기');h.appendChild(btn);box.id='market-panel-'+states.length;btn.setAttribute('aria-controls',box.id);
  function set(on){box.hidden=!on;h.classList.toggle('market-open',on);btn.textContent=on?'접기 −':'펼치기 +';btn.setAttribute('aria-expanded',String(on));}
  set(false);h.addEventListener('click',function(e){if(e.target.closest('a'))return;if(box.hidden)permit(function(){set(true);});else set(false);});h._set=function(on){if(on)permit(function(){set(true);});else set(false);};states.push({h:h,set:set,title:title});
 }
 // Fold section blocks, leaving the page title and live market overview visible.
 $$('main h2').filter(function(h){return !h.classList.contains('pg-title')&&!h.classList.contains('fold-h')&&!h.closest('.card,.scard,.p2p-hero')&&h.parentElement.classList.contains('wrap');}).forEach(function(h){var a=[],n=h.nextElementSibling;while(n&&n.tagName!=='H2'){a.push(n);n=n.nextElementSibling;}addFold(h,a);});
 // Product cards retain their existing node identities, tabs, forms and listeners.
 $$('main .card>h3,main .card>.fg-hd>h3').forEach(function(h){var card=h.closest('.card');if(card.closest('.market-fold-body')||card.querySelector('canvas,.dial'))return;var anchor=h.parentElement.classList.contains('fg-hd')?h.parentElement:h,nodes=[],n=anchor.nextElementSibling;while(n){nodes.push(n);n=n.nextElementSibling;}if(anchor!==h){var holder=document.createElement('div');holder.className='market-card-header';h.before(holder);holder.appendChild(h);Array.from(anchor.children).filter(function(x){return x!==holder;}).forEach(function(x){holder.appendChild(x);});addFold(h,nodes);}else addFold(h,nodes);});
 $$('main .wrap>h3').forEach(function(h){if(h.closest('.market-fold-body'))return;var a=[],n=h.nextElementSibling;while(n&&n.tagName!=='H2'&&n.tagName!=='H3'){a.push(n);n=n.nextElementSibling;}addFold(h,a);});
 // Trading strategy toggles are owned by the original trading engine.
 $$('[data-sc]',main).forEach(function(btn){var card=document.getElementById(btn.dataset.sc);if(!card)return;card.classList.remove('open');btn.classList.add('market-fold-btn');btn.setAttribute('aria-label',(card.querySelector('.ti')||card).textContent.trim()+' 펼치기/접기');function sync(){var on=card.classList.contains('open');btn.textContent=on?'접기 −':'펼치기 +';btn.setAttribute('aria-expanded',String(on));}sync();new MutationObserver(sync).observe(card,{attributes:true,attributeFilter:['class']});states.push({h:card.querySelector('.scard-h'),title:(card.querySelector('.ti')||card).textContent.trim(),set:function(on){if(card.classList.contains('open')!==on)btn.click();}});});
 $$('details',main).forEach(function(d){d.open=false;});
 var status=$('#pro-status'),bar=document.createElement('div');bar.className='cross-status-actions market-actions';
 var retry=$('#ps-rf');if(retry)bar.appendChild(retry);
 [['0','모두 접기','⊟'],['1','모두 펼치기','⊞']].forEach(function(x){var b=document.createElement('button');b.type='button';b.dataset.mobileIcon=x[2];b.setAttribute('aria-label',x[1]);b.title=x[1];var label=document.createElement('span');label.className='cross-action-label';label.textContent=x[1];b.appendChild(label);bar.appendChild(b);b.onclick=function(){var on=x[0]==='1',run=function(){states.forEach(function(s){s.set(on);});$$('details',main).forEach(function(d){d.open=on;});};if(on)permit(run);else run();};});
 if(retry){retry.setAttribute('aria-label','다시 불러오기');retry.title='다시 불러오기';retry.dataset.mobileIcon='↻';retry.innerHTML='<span class="cross-action-label">↻ 다시 불러오기</span>';}
 if(status)status.appendChild(bar);else main.prepend(bar);
 // Navigation uses current section headings; opening a section precedes scrolling.
 var toc=$('#pro-toc');if(!toc&&states.length){toc=document.createElement('nav');toc.id='pro-toc';toc.setAttribute('aria-label','페이지 바로가기');(status||$('header')).after(toc);}
 if(toc){toc.innerHTML='';var navItems=$$('main h2').map(function(h){return states.find(function(s){return s.h===h;})||{h:h,title:h.textContent.replace(/\s+/g,' ').trim(),set:function(){}};});states.forEach(function(s){if(!navItems.some(function(x){return x.h===s.h;}))navItems.push(s);});navItems.forEach(function(s,i){var a=document.createElement('a');a.href='#market-heading-'+i;s.h.id=s.h.id||'market-heading-'+i;a.href='#'+s.h.id;a.textContent=s.title.slice(0,18);a.title=s.title;toc.appendChild(a);a.onclick=function(e){e.preventDefault();e.stopPropagation();permit(function(){s.set(true);s.h.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});});};});}
 // Existing quick navigation items may point inside a newly collapsed group.
 document.addEventListener('click',function(e){var link=e.target.closest('a[href^="#"]');if(!link)return;var id=link.getAttribute('href').slice(1),target=id&&document.getElementById(id);if(!target)return;var closed=[];var node=target.parentElement;while(node){if(node.classList.contains('market-fold-body')&&node.hidden){var state=states.find(function(s){return s.h.nextElementSibling===node;});if(state)closed.unshift(state);}node=node.parentElement;}if(closed.length){e.preventDefault();permit(function(){closed.forEach(function(s){s.set(true);});target.scrollIntoView({behavior:'smooth',block:'start'});});}},true);
 var help=document.createElement('details');help.className='market-help';help.innerHTML='<summary>ⓘ 지표 읽는 법 · Help</summary><p><b>가격·환율</b>은 최근 수신 시세입니다. 시장 휴장이나 제공처 지연 시에는 최신 거래 시각을 확인하세요.</p><p><b>등락률</b>은 선택 기간의 기준 가격 대비 변화입니다. 상품 금리·수익률·수수료는 서로 다른 수치이므로 표의 단위를 확인하세요.</p><p><b>수익률 곡선</b>은 가격 흐름을 비교합니다. 배당·세금·수수료를 포함하는지는 해당 그래프의 설명을 확인하세요.</p><p><b>공모주·금융상품·P2P 일정</b>은 실제 신청 전 제공기관의 조건과 모집 상태를 확인하세요.</p>';main.appendChild(help);
 // Uniform quote and spark layout applies to asynchronously generated rows too.
 function tables(){ $$('table',main).forEach(function(t){if(t.dataset.marketTable)return;t.dataset.marketTable='1';if(!t.closest('.scroll')){var w=document.createElement('div');w.className='scroll market-scroll';t.before(w);w.appendChild(t);}var cols=$$('thead th',t);cols.forEach(function(th,i){if(/가격|현재가|종가|진입가|청산가|매수가|환율|매매기준율|금리|수익률/.test(th.textContent)){Array.from(t.rows).forEach(function(r){var c=r.cells[i];if(c)c.classList.add('market-number');});}});});}
 tables();var timer;new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(tables,200);}).observe(main,{childList:true,subtree:true});
 var up=$('#pro-top'),gift=$('#naver-gift-link');if(up){var floating=document.createElement('div');floating.className='cross-floating';if(gift){var g=document.createElement('a');g.href=gift.href;g.target='_blank';g.rel='noopener';g.className='cross-gift';g.textContent='🎁';g.setAttribute('aria-label','네이버포인트 선물하기');g.title='네이버포인트 선물하기';floating.appendChild(g);}floating.appendChild(up);B.appendChild(floating);var nav=$('#mk-tabbar');function measure(){B.style.setProperty('--cross-nav-height',nav?Math.round(nav.getBoundingClientRect().height)+'px':'0px');}measure();if(window.ResizeObserver&&nav)new ResizeObserver(measure).observe(nav);window.addEventListener('resize',measure);}
 var footer=$('footer');if(footer){var version=$('#mk-ver');if(version)version.hidden=true;var stamp=$('#stamp');if(stamp)stamp.hidden=true;var update=document.createElement('button');update.type='button';update.className='cross-update';update.textContent='업데이트 · 2026.10.11';footer.appendChild(update);function admin(){try{return localStorage.getItem('mk_gate_off')==='1';}catch(e){return false;}}function refreshAdmin(){update.disabled=!admin();}refreshAdmin();setInterval(refreshAdmin,4000);update.onclick=function(){if(!admin())return;var log=$('.cross-update-log',footer);if(!log){log=document.createElement('div');log.className='cross-update-log';log.innerHTML='<b>업데이트 이력</b><p>2026-10-11 · 공통 디자인 적용: 카드·버튼·여백, 기본 접힘·방문 중 펼침 유지, 전체 접기·펼치기, 가격 볼드·스파크라인 정렬, 모바일 조작, Help, 선물·맨 위로 위치.</p>';footer.appendChild(log);}else log.hidden=!log.hidden;};}
})();

}
;
(function(){
 document.body.classList.add('detail-v85');document.addEventListener('click',function(e){var h=e.target.closest('h2.fold-h:not(.open)');if(!h||!e.isTrusted||!window.MK_REQUEST_DETAIL)return;e.preventDefault();e.stopImmediatePropagation();var t=e.target;window.MK_REQUEST_DETAIL(function(){t.click();});},true);
 ['cf','kr'].forEach(function(pre){var value=document.getElementById(pre+'-val'),old=document.getElementById(pre+'-kimcomment');if(!value||!old)return;var box=document.createElement('div');box.id=pre+'-unified-comment';box.className='unified-comment';old.closest('.fg-row')?old.closest('.fg-row').after(box):old.after(box);old.hidden=true;var zones=['극단적 공포','공포','중립','탐욕','극단적 탐욕'],actions=['매수 시작','매수 시작','관망','매수 금지','매수 금지'],colors=['#C42318','#C2410C','#566074','#3F7D20','#0B6B3A'];function draw(){var text=value.textContent.trim(),n=Number(text);if(!text||!Number.isFinite(n)||n<0||n>100){box.textContent='공포탐욕 데이터 확인 필요';return;}var z=n<25?0:n<45?1:n<=55?2:n<=75?3:4;box.innerHTML='<div class="kc" style="--zc:'+colors[z]+'"><span class="kc-k">김군코멘트</span><div class="kc-t"><em>'+zones[z]+'</em><i>→</i><b>'+actions[z]+'</b></div><div class="kc-z">'+zones.map(function(t,i){return'<span class="'+(i===z?'on':'')+'">'+t+'</span>';}).join('')+'</div></div>'; }draw();new MutationObserver(draw).observe(value,{childList:true,characterData:true,subtree:true});});
 // Match the US floating stack, including icon shape, button height and the bottom navigation offset.
 var floating=document.querySelector('.cross-floating');if(floating){floating.classList.add('stock-floating-actions');var gift=floating.querySelector('.cross-gift');if(gift)gift.id='stock-gift';}
 // Native legacy folds already own the interaction; convert their visual span to an accessible button.
 document.querySelectorAll('h2.fold-h').forEach(function(h){var old=h.querySelector('span.fold-btn');if(!old)return;var b=document.createElement('button');b.type='button';b.className='fold-btn';b.innerHTML=old.innerHTML;b.setAttribute('aria-label',(h.querySelector('.fold-t')||h).textContent.trim()+' 펼치기/접기');old.replaceWith(b);if(h._set){var previous=h._set;h._set=function(on){previous(on);b.innerHTML=on?'<em>접기</em> −':'<em>펼치기</em> +';b.setAttribute('aria-expanded',String(on));};h.addEventListener('click',function(){var on=h.classList.contains('open');b.innerHTML=on?'<em>접기</em> −':'<em>펼치기</em> +';b.setAttribute('aria-expanded',String(on));});}new MutationObserver(function(){var on=h.classList.contains('open');b.innerHTML=on?'<em>접기</em> −':'<em>펼치기</em> +';b.setAttribute('aria-expanded',String(on));}).observe(h,{attributes:true,attributeFilter:['class']});h.removeAttribute('role');h.removeAttribute('tabindex');});
 // Avoid nested fold controls: one full-width header governs each card.
 document.querySelectorAll('.market-card-header').forEach(function(holder){var h=holder.querySelector('h3.market-fold-h');if(!h)return;holder.classList.add('market-card-header-full');});
})();

;
(function(){['cf','kr'].forEach(function(pre){
 var card=document.getElementById(pre==='cf'?'cf-dial':'kr-card'),source=document.getElementById(pre+'-val');
 if(card&&source){if(pre==='cf')card=card.closest('.card');var existing=card.querySelector('.stock-gauge');if(existing)return;
  var h=card.querySelector('.fg-hd h3');if(h)Array.from(h.childNodes).forEach(function(n){if(n.nodeType===3)n.textContent=n.textContent.replace('🇺🇸','').trim();});
  var gauge=document.createElement('a');gauge.className='stock-gauge';gauge.href='https://www.cnn.com/markets/fear-and-greed';gauge.target='_blank';gauge.rel='noopener noreferrer';
  gauge.innerHTML='<svg viewBox="0 0 240 160" role="img" aria-label="공포탐욕지수 연결 중"><g class="sg-segments"></g><path class="sg-pointer" fill="currentColor" hidden></path><text class="sg-value" x="120" y="111" text-anchor="middle">—</text><text class="sg-label" x="120" y="137" text-anchor="middle">데이터 연결 중</text><text class="sg-edge" x="19" y="147" text-anchor="start">공포 0</text><text class="sg-edge" x="221" y="147" text-anchor="end">100 탐욕</text></svg>';
  var svg=gauge.querySelector('svg'),group=gauge.querySelector('.sg-segments'),colors=['#ef8e86','#f3c17a','#e7dba0','#9bd5ba','#4bb792'];
  function point(angle,r){return [120+Math.cos(angle)*r,119-Math.sin(angle)*r];}
  colors.forEach(function(color,i){var start=point(Math.PI-i*Math.PI/5-.02,94),end=point(Math.PI-(i+1)*Math.PI/5+.02,94),p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M '+start.join(' ')+' A 94 94 0 0 1 '+end.join(' '));p.setAttribute('fill','none');p.setAttribute('stroke',color);p.setAttribute('stroke-width','17');group.appendChild(p);});
  var dial=document.getElementById(pre+'-dial');if(dial){dial.before(gauge);dial.style.display='none';}
  var insights=document.createElement('details');insights.className='stock-insights-details';var title=document.createElement('summary');title.textContent='지수 해석·관련 일정 보기';insights.appendChild(title);
  [pre+'-unified-comment',pre+'-next-event'].forEach(function(id){var e=document.getElementById(id);if(e)insights.appendChild(e);});
  card.appendChild(insights);
  function syncGauge(){
   var text=source.textContent.trim(),n=Number(text),ok=text!==''&&Number.isFinite(n)&&n>=0&&n<=100;
   gauge.querySelector('.sg-value').textContent=ok?String(Math.round(n)):'—';
   var label=ok?(n<25?'극단적 공포':n<45?'공포':n<=55?'중립':n<=75?'탐욕':'극단적 탐욕'):'데이터 연결 중';
   gauge.querySelector('.sg-label').textContent=label;svg.setAttribute('aria-label',ok?'공포탐욕지수 '+Math.round(n)+'점 · '+label:'공포탐욕지수 연결 중');
   var arrow=gauge.querySelector('.sg-pointer');arrow.style.display=ok?'':'none';
   if(ok){arrow.removeAttribute('hidden');var a=Math.PI*(1-n/100),tip=point(a,108),left=point(a-.065,82),right=point(a+.065,82);arrow.setAttribute('d','M '+tip.join(' ')+' L '+left.join(' ')+' L '+right.join(' ')+' Z');}
  }
  insights.open=matchMedia('(min-width:701px)').matches;syncGauge();new MutationObserver(syncGauge).observe(source,{childList:true,subtree:true,characterData:true});
 }
 
});})();

;
(function(){
 'use strict';if(document.getElementById('unified-tools'))return;
 var main=document.querySelector('main');if(!main)return;
 var $=function(s,r){return(r||document).querySelector(s);},esc=function(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});},RE=/^[A-Z0-9.^=\-]{1,20}$/;
 function permit(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function read(key,fallback){try{return JSON.parse((key==='mk_hold'&&localStorage.getItem('stock_account_persist')!=='1'&&!localStorage.getItem(key)?sessionStorage:localStorage).getItem(key)||'null')||fallback;}catch(e){return fallback;}}
 function save(key,v){try{(key==='mk_hold'&&localStorage.getItem('stock_account_persist')!=='1'?sessionStorage:localStorage).setItem(key,JSON.stringify(v));}catch(e){}}
 function money(n,c){return Number.isFinite(n)?new Intl.NumberFormat('ko-KR',{style:'currency',currency:c||'USD',maximumFractionDigits:c==='KRW'?0:2}).format(n):'—';}
 function pct(n){return Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'—';}
 var cache={};
 async function quote(t,range){var key=t+'|'+(range||'1y');if(cache[key]&&Date.now()-cache[key].at<60000)return cache[key].data;var url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(t)+'?range='+(range||'1y')+'&interval=1d';var j=typeof getJSON==='function'?await getJSON(url):await fetch('https://ai.coolzet.workers.dev/?url='+encodeURIComponent(url)).then(function(r){if(!r.ok)throw Error('조회 실패');return r.json();});var r=j&&j.chart&&j.chart.result&&j.chart.result[0];if(!r)throw Error('조회 실패');var cl=r.indicators.quote[0].close,points=r.timestamp.map(function(ts,i){return{t:ts*1000,v:cl[i],d:new Date(ts*1000).toISOString().slice(0,10)};}).filter(function(x){return Number.isFinite(x.v)&&x.v>0;});if(!points.length)throw Error('시세 없음');var px=r.meta.regularMarketPrice||points[points.length-1].v,day=new Date((r.meta.regularMarketTime||r.timestamp[r.timestamp.length-1])*1000).toISOString().slice(0,10),older=points.filter(function(p){return p.d<day;}),prev=older.length?older[older.length-1].v:null;var result={t:t,currency:r.meta.currency||'USD',px:px,pct:prev?100*(px/prev-1):null,points:points};cache[key]={at:Date.now(),data:result};return result;}
 var hub=document.createElement('details');hub.id='unified-tools';hub.className='unified-tools';hub.innerHTML='<summary>내 투자 도구</summary><nav aria-label="내 투자 도구"><button type="button" data-tool="watch" aria-pressed="true">☆ 관심종목</button><button type="button" data-tool="account" aria-pressed="false">▣ 내계좌</button><button type="button" data-tool="compare" aria-pressed="false">⌕ 종목비교</button></nav><p class="ut-hint">미국주식 AAPL · 한국주식 005930.KS · 가상화폐 BTC-USD · 환율 KRW=X<br>저장 정보는 같은 사이트의 페이지에서 공유됩니다.</p><section data-panel="watch"><h3>내 관심종목</h3><form><label>종목 티커<input name="ticker" required maxlength="20" placeholder="AAPL / 005930.KS / BTC-USD"></label><button>＋ 추가</button></form><div class="ut-watch" role="status"></div></section><section data-panel="account" hidden><h3>내계좌 · 손익·비중</h3><form><label>종목 티커<input name="ticker" required maxlength="20"></label><label>보유 수량<input name="quantity" type="number" min="0.00000001" step="any" required></label><label>평균단가 · 해당 종목 통화<input name="cost" type="number" min="0" step="any" required></label><button>＋ 추가·수정</button></form><label class="ut-save"><input type="checkbox">이 기기에 계좌 정보 계속 저장</label><p class="ut-hint">평가금액·손익·비중은 통화별로 계산합니다. 통화가 다른 종목을 합산하지 않습니다.</p><div class="ut-account" role="status"></div><label>수익률 기간<select class="ut-account-period"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button type="button" class="ut-account-curve">계좌 수익률 곡선</button><div class="ut-account-chart" role="status"></div></section><section data-panel="compare" hidden><h3>종목비교 · 수익률 곡선</h3><form><label>비교 종목 · 최대 3개<input name="symbols" placeholder="QQQ, TQQQ, SCHD" required></label><label>기간<select name="months"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button>비교하기</button></form><div class="ut-compare-chart" role="status"></div></section><p class="ut-message" role="status" aria-live="polite"></p></details>';main.appendChild(hub);
 hub.querySelector('summary').addEventListener('click',function(e){if(hub.open)return;e.preventDefault();permit(function(){hub.open=true;});});
 hub.querySelector('nav').addEventListener('click',function(e){var b=e.target.closest('[data-tool]');if(!b)return;hub.querySelectorAll('[data-panel]').forEach(function(p){p.hidden=p.dataset.panel!==b.dataset.tool;});hub.querySelectorAll('[data-tool]').forEach(function(x){x.setAttribute('aria-pressed',String(x===b));});if(b.dataset.tool==='watch')watch();if(b.dataset.tool==='account')account();});
 function message(s){$('.ut-message',hub).textContent=s;}
 var watchSeq=0;
 async function watch(){var seq=++watchSeq,list=read('mk_my_tickers',[]).filter(function(t){return RE.test(t);}).slice(0,20),box=$('.ut-watch',hub);if(!list.length){box.textContent='종목을 추가하면 가격과 등락률이 표시됩니다.';return;}box.textContent='관심종목 시세를 불러오는 중…';var results=await Promise.all(list.map(async function(t){try{return await quote(t);}catch(e){return {t:t};}}));if(seq!==watchSeq)return;box.innerHTML=results.map(function(r){return '<div class="ut-row"><b>'+esc(r.t)+'</b><div class="ut-spark">'+spark(r.points)+'</div><div><b>'+money(r.px,r.currency)+'</b><strong>'+pct(r.pct)+'</strong></div><button type="button" data-remove-watch="'+esc(r.t)+'" aria-label="'+esc(r.t)+' 삭제">×</button></div>';}).join('');}
 function spark(points){if(!points||points.length<2)return '';var a=points.slice(-30),lo=Math.min.apply(null,a.map(function(p){return p.v;})),hi=Math.max.apply(null,a.map(function(p){return p.v;})),d=a.map(function(p,i){return(i?'L':'M')+(i/(a.length-1)*72).toFixed(1)+' '+(26-(p.v-lo)/(hi-lo||1)*24).toFixed(1);}).join(' ');return '<svg viewBox="0 0 72 28" aria-hidden="true"><path d="'+d+'" stroke="var(--accent)" fill="none" stroke-width="2"/></svg>';}
 $('[data-panel=watch] form',hub).onsubmit=async function(e){e.preventDefault();var input=this.elements.ticker,t=input.value.trim().toUpperCase(),list=read('mk_my_tickers',[]);if(!RE.test(t)){message('티커 형식을 확인하세요.');return;}if(list.includes(t))return;if(list.length>=20){message('관심종목은 최대 20개까지 저장할 수 있습니다.');return;}try{await quote(t);list.push(t);save('mk_my_tickers',list);input.value='';message('추가했습니다.');watch();}catch(e){message('시세를 찾지 못했습니다. 티커를 확인하세요.');}};
 hub.addEventListener('click',function(e){var b=e.target.closest('[data-remove-watch]');if(b){save('mk_my_tickers',read('mk_my_tickers',[]).filter(function(t){return t!==b.dataset.removeWatch;}));watch();}b=e.target.closest('[data-remove-hold]');if(b){var h=read('mk_hold',{});delete h[b.dataset.removeHold];save('mk_hold',h);account();}b=e.target.closest('[data-edit-hold]');if(b){var h=read('mk_hold',{})[b.dataset.editHold],f=$('[data-panel=account] form',hub);f.elements.ticker.value=b.dataset.editHold;f.elements.quantity.value=h.q;f.elements.cost.value=h.c||0;f.elements.ticker.focus();}});
 $('[data-panel=account] form',hub).onsubmit=async function(e){e.preventDefault();var t=this.elements.ticker.value.trim().toUpperCase(),q=+this.elements.quantity.value,c=+this.elements.cost.value;if(!RE.test(t)||!(q>0)||!Number.isFinite(q)||!(c>=0)||!Number.isFinite(c)){message('티커·수량·평균단가를 확인하세요.');return;}var h=read('mk_hold',{});if(Object.keys(h).length>=30&&!h[t]){message('계좌는 최대 30종목까지 입력할 수 있습니다.');return;}try{await quote(t);h[t]={q:q,c:c||null};save('mk_hold',h);this.reset();message('계좌 정보를 저장했습니다.');account();}catch(e){message('시세를 확인할 수 없어 저장하지 않았습니다.');}};
 var keep=$('.ut-save input',hub);keep.checked=localStorage.getItem('stock_account_persist')==='1';keep.onchange=function(){var h=read('mk_hold',{});localStorage.setItem('stock_account_persist',keep.checked?'1':'0');localStorage.removeItem('mk_hold');sessionStorage.removeItem('mk_hold');save('mk_hold',h);};
 var accountSeq=0;
 async function account(){var seq=++accountSeq,h=read('mk_hold',{}),keys=Object.keys(h),box=$('.ut-account',hub);if(!keys.length){box.textContent='보유 종목을 입력하면 평가금액·손익·비중을 계산합니다.';return;}box.textContent='계좌 시세를 불러오는 중…';var rows=await Promise.all(keys.map(async function(t){try{var r=await quote(t);return Object.assign({},r,{q:h[t].q,c:h[t].c,total:r.px*h[t].q,profit:h[t].c==null?null:(r.px-h[t].c)*h[t].q});}catch(e){return{t:t,q:h[t].q,c:h[t].c};}}));if(seq!==accountSeq)return;var totals={};rows.forEach(function(r){if(r.currency)totals[r.currency]=(totals[r.currency]||0)+r.total;});box.innerHTML='<div class="ut-totals">'+Object.keys(totals).map(function(c){return'<b>'+c+' 평가금액 '+money(totals[c],c)+'</b>';}).join('')+'</div><table><thead><tr><th>종목</th><th>수량</th><th>평균단가</th><th>현재가</th><th>평가금액</th><th>손익</th><th>등락률</th><th>비중</th><th>관리</th></tr></thead><tbody>'+rows.map(function(r){return '<tr>'+[r.t,String(r.q),money(r.c,r.currency),money(r.px,r.currency),money(r.total,r.currency),money(r.profit,r.currency),pct(r.pct),r.currency?pct(100*r.total/totals[r.currency]):'—'].map(function(s,i){return'<td data-label="'+['종목','수량','평균단가','현재가','평가금액','손익','등락률','비중'][i]+'">'+esc(s)+'</td>';}).join('')+'<td><button type="button" data-edit-hold="'+esc(r.t)+'">수정</button><button type="button" data-remove-hold="'+esc(r.t)+'">삭제</button></td></tr>';}).join('')+'</tbody></table>'+(rows.some(function(r){return!r.currency;})?'<p>일부 시세를 불러오지 못했습니다. 해당 종목은 합계에서 제외됩니다.</p>':'');}
 function cutoff(end,months){var d=new Date(end),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-months);d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()));return +d;}
 function draw(box,series,note){if(!series.length){box.textContent='공통 시세 구간이 부족합니다.';return;}var lo=Math.min(0,...series.flatMap(function(s){return s.y;})),hi=Math.max(0,...series.flatMap(function(s){return s.y;}));if(lo===hi){lo-=1;hi+=1;}var W=760,H=300,L=65,R=20,T=24,D=50,pw=W-L-R,ph=H-T-D,colors=['#16865c','#4386db','#d5872a','#835ad8'],start=Math.min(...series.map(function(s){return s.ts[0];})),end=Math.max(...series.map(function(s){return s.ts[s.ts.length-1];})),x=function(t){return L+(t-start)/(end-start||1)*pw;},y=function(v){return T+(hi-v)/(hi-lo)*ph;},grid='';for(var i=0;i<5;i++){var v=lo+(hi-lo)*i/4;grid+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y(v)+'" y2="'+y(v)+'" stroke="currentColor" opacity=".12"/><text x="'+(L-8)+'" y="'+(y(v)+4)+'" text-anchor="end">'+v.toFixed(1)+'%</text>';}[start,(start+end)/2,end].forEach(function(t){grid+='<text x="'+x(t)+'" y="'+(H-24)+'" text-anchor="middle">'+new Date(t).toISOString().slice(0,10)+'</text>';});box.innerHTML='<div class="ut-legend">'+series.map(function(s,i){return'<b style="color:'+colors[i%colors.length]+'">'+esc(s.name)+' '+pct(s.y[s.y.length-1])+'</b>';}).join('')+'</div><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="수익률 비교. 세로축 수익률 퍼센트, 가로축 날짜"><g fill="currentColor" font-size="11">'+grid+'<text x="'+L+'" y="14">수익률(%)</text><text x="380" y="296" text-anchor="middle">날짜</text></g>'+series.map(function(s,i){return'<path fill="none" stroke="'+colors[i%colors.length]+'" stroke-width="2" '+(s.benchmark?'stroke-dasharray="6 3"':'')+'d="'+s.y.map(function(v,j){return(j?'L':'M')+x(s.ts[j]).toFixed(1)+' '+y(v).toFixed(1);}).join(' ')+'"/>';}).join('')+'</svg><p>'+esc(note)+'</p>';}
 $('[data-panel=compare] form',hub).onsubmit=async function(e){e.preventDefault();var ts=this.elements.symbols.value.toUpperCase().split(/[ ,]+/).filter(Boolean),months=+this.elements.months.value,box=$('.ut-compare-chart',hub);if(ts.length>3||!ts.length||ts.some(function(t){return!RE.test(t);})){message('올바른 티커를 최대 3개 입력하세요.');return;}box.textContent='수익률을 불러오는 중…';try{var data=await Promise.all(ts.map(function(t){return quote(t,'10y');})),end=Math.min(...data.map(function(r){return r.points[r.points.length-1].t;})),start=cutoff(end,months);var series=data.map(function(r){var a=r.points.filter(function(p){return p.t>=start&&p.t<=end;});if(a.length<2)throw Error('기간 부족');return{name:r.t,ts:a.map(function(p){return p.t;}),y:a.map(function(p){return 100*(p.v/a[0].v-1);})};});draw(box,series,'가격 수익률 · 배당·세금·환율 제외 · 시세가 제공되는 실제 기간만 표시합니다.');}catch(e){box.textContent='선택한 종목의 수익률을 불러오지 못했습니다.';}};
 $('.ut-account-curve',hub).onclick=async function(){var h=read('mk_hold',{}),keys=Object.keys(h),box=$('.ut-account-chart',hub),months=+$('.ut-account-period',hub).value;if(!keys.length){box.textContent='보유 종목을 먼저 입력하세요.';return;}box.textContent='계좌 곡선을 불러오는 중…';try{var data=await Promise.all(keys.map(function(t){return quote(t,'10y');})),currencies=Array.from(new Set(data.map(function(r){return r.currency;})));if(currencies.length!==1){box.textContent='계좌 곡선은 동일 통화 종목만 계산할 수 있습니다. 여러 통화의 금액을 임의로 합산하지 않습니다.';return;}var end=Math.min(...data.map(function(r){return r.points[r.points.length-1].t;})),start=cutoff(end,months),maps=data.map(function(r){return new Map(r.points.map(function(p){return[p.d,p];}));}),common=data[0].points.filter(function(p){return p.t>=start&&p.t<=end&&maps.every(function(m){return m.has(p.d);});});if(common.length<2)throw Error('공통 날짜 부족');var values=common.map(function(p){return data.reduce(function(sum,r,i){return sum+maps[i].get(p.d).v*h[r.t].q;},0);}),series=[{name:'내계좌 '+currencies[0],ts:common.map(function(p){return p.t;}),y:values.map(function(v){return100(v/values[0]-1);})}];var bm=currencies[0]==='KRW'?'^KS11':'QQQ';try{var bench=await quote(bm,'10y'),map=new Map(bench.points.map(function(p){return[p.d,p];})),points=common.filter(function(p){return map.has(p.d);});if(points.length>1){var base=map.get(points[0].d).v,valueMap=new Map(common.map(function(p,i){return[p.d,values[i]];})),accountBase=valueMap.get(points[0].d);series[0]={name:series[0].name,ts:points.map(function(p){return p.t;}),y:points.map(function(p){return100(valueMap.get(p.d)/accountBase-1);})};series.push({name:bm+' 벤치마크',benchmark:true,ts:points.map(function(p){return p.t;}),y:points.map(function(p){return100(map.get(p.d).v/base-1);})});}}catch(e){}draw(box,series,'현재 수량을 과거에도 동일하게 보유한 가격 수익률 시뮬레이션입니다. 실제 거래·입출금·배당·환율은 반영하지 않습니다.');}catch(e){box.textContent='일부 종목의 시세가 없어 계좌 곡선을 계산할 수 없습니다.';}};
 function return100(n){return n*100;}
 window.MK_MY_ADD=async function(t){t=String(t).trim().toUpperCase();if(!RE.test(t))return false;var list=read('mk_my_tickers',[]);if(list.includes(t))return true;if(list.length>=20)return false;try{await quote(t);list.push(t);save('mk_my_tickers',list);watch();return true;}catch(e){return false;}};
 function investment(){permit(function(){hub.open=true;hub.scrollIntoView({behavior:'smooth',block:'start'});watch();});}
 var toc=$('#pro-toc');if(toc){var btn=document.createElement('button');btn.type='button';btn.className='unified-invest-link';btn.textContent='내 투자';btn.onclick=investment;toc.appendChild(btn);}document.addEventListener('click',function(e){var b=e.target.closest('#mk-tabbar button');if(b&&/내 투자|내투자/.test(b.textContent)){e.preventDefault();e.stopImmediatePropagation();investment();}},true);
 hub.addEventListener('toggle',function(){if(hub.open)watch();});window.addEventListener('storage',function(){if(hub.open){watch();account();}});
})();

}
(function(){
 'use strict';
 var body=document.body,main=document.querySelector('main');if(!main)return;
 body.classList.add('design-v86');var page=location.pathname.split('/').pop().replace('.html','');
 var labels={'stock':'미국주식 시장 대시보드','kr-stock':'한국주식 시장 대시보드',crypto:'가상화폐 시장 대시보드',bond:'채권 시장 대시보드',finprod:'금융상품',ipo:'공모주',p2p:'P2P',fx:'환율 시장 대시보드',trade:'매매김군', 'mrkim-signal':'Mr.Kim Signal'};
 var descriptions={crypto:'시장 심리와 주요 코인 가격을 한눈에 확인하세요.',bond:'등급별 금리·만기·채권 수익률을 비교하세요.',finprod:'금리·가입 기간·상품 조건을 비교하세요.',ipo:'청약 일정·공모가·상장 진행 상태를 확인하세요.',p2p:'수익률·기간·상환 방식과 상품 상태를 확인하세요.',fx:'주요 통화의 환율과 최근 흐름을 확인하세요.',trade:'전략 입력과 성과를 단계별로 확인하세요.','kr-stock':'시장 심리·투자자 동향·주요 일정을 한눈에 확인하세요.'};
 if(page!=='stock'&&page!=='mrkim-signal'){
  var head=document.createElement('div');head.className='v86-page-head';var eyebrow=document.createElement('p');eyebrow.className='v86-eyebrow';eyebrow.textContent='MR.KIM SIGNAL';var title=document.createElement('h1');title.textContent=labels[page]||document.title;var description=document.createElement('p');description.textContent=descriptions[page]||'';head.append(eyebrow,title,description);main.prepend(head);
  var old=document.querySelector('#'+page+' > .wrap > .sec-h, #'+page+' > .wrap > h1, main .hero h1');if(old)old.hidden=true;
  var status=document.getElementById('pro-status');if(status)head.after(status);
  var toc=document.getElementById('pro-toc');var brief=document.getElementById('pro-brief');if(toc)(brief||status||head).after(toc);
 }
 var ps=document.getElementById('pro-status');if(ps&&!ps.querySelector('[aria-label="다시 불러오기"]')){var actions=ps.querySelector('.cross-status-actions,.cross-fold-all,.fold-all');if(!actions){actions=document.createElement('div');actions.className='cross-status-actions';ps.append(actions);}var retry=document.createElement('button');retry.type='button';retry.setAttribute('aria-label','다시 불러오기');retry.title='다시 불러오기';retry.dataset.mobileIcon='↻';retry.innerHTML='<span class="cross-action-label">다시 불러오기</span>';retry.onclick=function(){location.reload();};actions.prepend(retry);}
 if(page==='kr-stock'){
  var repeated=document.querySelector('#pro-brief .pb-line');if(repeated)repeated.hidden=true;
  var originalTitle=document.querySelector('#kr-stock .pg-title, #kr-stock .pg-h1');if(originalTitle){originalTitle.hidden=true;var intro=originalTitle.nextElementSibling;if(intro&&intro.matches('.sub,.pg-lead'))intro.hidden=true;}
  var guide=document.getElementById('guide');if(guide&&!guide.querySelector('details')){var d=document.createElement('details'),s=document.createElement('summary');s.textContent='지표 읽는 법 · Help';d.append(s);Array.from(guide.children).forEach(function(n){if(n.id==='guide-h')n.hidden=true;else d.append(n);});guide.append(d);}
  var gauge=document.querySelector('#kr-card .stock-gauge');if(gauge){gauge.href='#guide';gauge.removeAttribute('target');gauge.addEventListener('click',function(){var d=document.querySelector('#guide details');if(d)d.open=true;});}
 }
 var cryptoGauge=document.querySelector('#cr-top .stock-gauge');if(cryptoGauge)cryptoGauge.href='https://alternative.me/crypto/fear-and-greed-index/';
 // A single shell groups existing links without replacing their event handlers.
 var toc=document.getElementById('pro-toc');if(toc&&page!=='stock'){
  toc.classList.add('v86-toc');var links=Array.from(toc.children),groups={market:[],analysis:[],calendar:[]};
  links.forEach(function(n){var t=n.textContent.trim();if(/검색|요약|내 투자/.test(t))return;groups[/일정|이벤트|청약/.test(t)?'calendar':/TOP|레버리지|종목|수익률|편입|편출|전략|코인/.test(t)?'analysis':'market'].push(n);});
  [['market','시장지표'],['analysis','종목분석'],['calendar','일정']].forEach(function(pair){if(!groups[pair[0]].length)return;var d=document.createElement('details'),s=document.createElement('summary'),box=document.createElement('div');s.textContent=pair[1];box.className='v86-menu';d.append(s,box);toc.append(d);groups[pair[0]].forEach(function(n){box.append(n);n.addEventListener('click',function(){d.open=false;});});});
 }
 if(page==='mrkim-signal'){
  var hero=document.querySelector('.hero .wrap');if(hero){var p=hero.querySelector('.hero-p');if(p)p.textContent='시장별 핵심 지표와 내 투자 도구를 확인하세요.';var links=hero.querySelector('.cross-market-links');if(!links){links=document.createElement('nav');links.className='cross-market-links';hero.append(links);}links.replaceChildren();[['stock','미국주식','공포탐욕 · VIX · 섹터'],['kr-stock','한국주식','공포탐욕 · 수급 · 일정'],['crypto','가상화폐','시장 심리 · 주요 코인'],['bond','채권','금리 · 만기 · 수익률'],['finprod','금융상품','금리 · 가입 조건'],['ipo','공모주','청약 · 상장 일정'],['p2p','P2P','수익률 · 상환 조건'],['fx','환율','통화별 환율 · 흐름'],['trade','매매김군','전략 · 성과 비교']].forEach(function(x){var a=document.createElement('a'),b=document.createElement('b'),small=document.createElement('small');a.href=x[0]+'.html';b.textContent=x[1];small.textContent=x[2];a.append(b,small);links.append(a);});}
 }
 // Label responsive financial tables using the actual column names, never guessed units.
 function labelTables(){main.querySelectorAll('table').forEach(function(t){var heads=Array.from(t.querySelectorAll('thead th'));if(!heads.length)return;if(/^(bond|finprod|p2p|ipo|fx)$/.test(page)&&heads.length>4&&!t.closest('.unified-tools'))t.classList.add('v86-wide-table');Array.from(t.tBodies).forEach(function(tb){Array.from(tb.rows).forEach(function(r){Array.from(r.cells).forEach(function(c,i){if(heads[i])c.dataset.label=heads[i].textContent.trim();});});});});}
 labelTables();var pending;new MutationObserver(function(){clearTimeout(pending);pending=setTimeout(labelTables,100);}).observe(main,{subtree:true,childList:true});
 var footer=document.querySelector('footer');if(footer){var log=footer.querySelector('.cross-update-log');if(log){var entry=document.createElement('p');entry.textContent='2026-10-11 · 전체 페이지 표준화: 상단 순서, 메뉴 그룹, 카드·수치·접기 버튼, 모바일 간격, 출처 링크, 메인 진입 통일.';log.prepend(entry);}}
})();
