(function(){
 'use strict';
 var B=document.body,KR=B.classList.contains('kr');B.classList.add('cross-v83');
 var $=function(s,r){return(r||document).querySelector(s);},$$=function(s,r){return Array.from((r||document).querySelectorAll(s));};
 function detail(fn){if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();}
 function foldCard(card){
  if(!card)return;var h=$('h3',card);if(!h||h.dataset.crossFold)return;h.dataset.crossFold='1';var wasOpen=card.classList.contains('cross-open');card.classList.add('cross-fold','m-fold');
  var title=document.createElement('span');while(h.firstChild)title.appendChild(h.firstChild);h.appendChild(title);
  var btn=document.createElement('button');btn.type='button';btn.className='m-fold-btn';btn.setAttribute('aria-label',title.textContent+' 펼치기/접기');h.appendChild(btn);
  function set(on){card.classList.toggle('cross-open',on);card.classList.toggle('m-open',on);btn.innerHTML=on?'<em>접기</em> −':'<em>펼치기</em> +';btn.setAttribute('aria-expanded',String(on));}
  set(wasOpen);h.addEventListener('click',function(e){if(e.target.closest('a'))return;if(card.classList.contains('cross-open'))set(false);else detail(function(){set(true);});});
 }
 if(KR){
  var sub=$('#kr-sub');foldCard(sub&&sub.closest('.card'));
  var guide=$('#guide-h');if(guide&&!guide.classList.contains('fold-h')){var dl=guide.nextElementSibling;if(dl&&dl.tagName==='DL'){var help=document.createElement('button');help.type='button';help.className='cross-help';help.textContent='Help ⓘ';help.setAttribute('aria-expanded','false');guide.appendChild(help);dl.hidden=true;help.onclick=function(){dl.hidden=!dl.hidden;help.setAttribute('aria-expanded',String(!dl.hidden));};}}
  var tape=$('#pro-tick'),brief=$('#pro-brief');
  if(tape&&brief){
   var market=document.createElement('details');market.className='cross-restricted';var summary=document.createElement('summary');summary.textContent='주요 지수·환율';market.appendChild(summary);market.appendChild(tape);brief.appendChild(market);market.open=false;
   var track=document.createElement('div');track.className='cross-ticker-track';var first=document.createElement('div');first.className='cross-ticker-group';while(tape.firstChild)first.appendChild(tape.firstChild);track.appendChild(first);tape.appendChild(track);
   var second=document.createElement('div');second.className='cross-ticker-group';second.setAttribute('aria-hidden','true');second.inert=true;track.appendChild(second);
   function sync(){second.innerHTML=first.innerHTML;$$('[id]',second).forEach(function(e){e.removeAttribute('id');});}
   sync();new MutationObserver(sync).observe(first,{childList:true,subtree:true,characterData:true,attributes:true});
   summary.addEventListener('click',function(e){if(market.open)return;e.preventDefault();detail(function(){market.open=true;});});
  }
  var status=$('#pro-status'),bar=$('.fold-all');if(status){var actions=document.createElement('div');actions.className='cross-status-actions';var retry=$('#ps-rf');if(retry)actions.appendChild(retry);if(bar)actions.appendChild(bar);status.appendChild(actions);$$('button',actions).forEach(function(btn){var isRetry=btn.id==='ps-rf';btn.dataset.mobileIcon=isRetry?'↻':btn.dataset.o==='0'?'⊟':'⊞';btn.setAttribute('aria-label',isRetry?'다시 불러오기':btn.dataset.o==='0'?'모두 접기':'모두 펼치기');var span=document.createElement('span');span.className='cross-action-label';while(btn.firstChild)span.appendChild(btn.firstChild);btn.appendChild(span);});}
  var pulse=$('.pulse');if(pulse){foldCard(pulse);pulse.addEventListener('mouseenter',function(){if(matchMedia('(hover:hover)').matches)detail(function(){pulse.classList.add('cross-open','m-open');var btn=$('.m-fold-btn',pulse);if(btn){btn.innerHTML='<em>접기</em> −';btn.setAttribute('aria-expanded','true');}});});}
  new MutationObserver(function(){foldCard($('.pulse'));}).observe($('#main')||document.body,{childList:true,subtree:true});
 }else{
  var hero=$('.hero .wrap')||$('main .wrap');if(hero){
   var links=document.createElement('nav');links.className='cross-market-links';links.setAttribute('aria-label','시장 대시보드');
   [['stock.html','🇺🇸 미국주식','공포탐욕 · VIX · 핵심 종목 · 경제일정'],['kr-stock.html','🇰🇷 한국주식','코스피 · 코스닥 · 투자자 동향 · 주요 종목'],['crypto.html','₿ 가상화폐','시장 심리 · 주요 코인 · 시장 흐름']].forEach(function(x){var a=document.createElement('a');a.href=x[0];a.className='cross-market-link';var b=document.createElement('b');b.textContent=x[1];var s=document.createElement('span');s.textContent=x[2];var em=document.createElement('em');em.textContent='대시보드 열기 →';a.append(b,s,em);links.appendChild(a);});hero.appendChild(links);
   var help=document.createElement('details');help.className='cross-home-guide';help.innerHTML='<summary>ⓘ 지표 읽는 법 · Help</summary><p><b>공포탐욕지수</b>는 시장 심리를 0~100으로 나타냅니다. 낮을수록 공포, 높을수록 탐욕에 가깝습니다.</p><p><b>등락률</b>은 선택한 기간의 기준 가격 대비 변화입니다. 휴장일에는 최근 수신 시세를 확인하세요.</p><p><b>수익률 곡선</b>은 기간별 가격 흐름을 비교합니다. 과거 성과는 미래 수익을 보장하지 않습니다.</p>';hero.appendChild(help);
  }
 }
 var up=$('#pro-top'),gift=$('#naver-gift-link');if(up){var floating=document.createElement('div');floating.className='cross-floating';if(gift){var g=document.createElement('a');g.href=gift.href;g.target='_blank';g.rel='noopener';g.className='cross-gift';g.textContent='🎁';g.title='네이버포인트 선물하기';g.setAttribute('aria-label',g.title);floating.appendChild(g);}floating.appendChild(up);B.appendChild(floating);var nav=$('#mk-tabbar');function measure(){B.style.setProperty('--cross-nav-height',nav?Math.round(nav.getBoundingClientRect().height)+'px':'0px');}measure();if(window.ResizeObserver&&nav)new ResizeObserver(measure).observe(nav);window.addEventListener('resize',measure);}
 var stamp=$('#stamp');if(stamp)stamp.hidden=true;var footer=$('footer');if(footer){var version=$('#mk-ver');if(version)version.hidden=true;var updated=document.createElement('button');updated.type='button';updated.className='cross-update';updated.textContent='업데이트 · 2026.10.11';footer.appendChild(updated);function isAdmin(){try{return localStorage.getItem('mk_gate_off')==='1';}catch(e){return false;}}updated.disabled=!isAdmin();updated.addEventListener('click',function(){if(!isAdmin())return;var log=$('.cross-update-log',footer);if(!log){log=document.createElement('div');log.className='cross-update-log';log.innerHTML='<b>업데이트 이력</b><p>2026-10-11 · 미국주식 공통 디자인 적용: 카드·여백·종목 가격·스파크라인 정렬, 모바일 상태 버튼, 접기·펼치기, 지수 티커, 도움말, 선물·맨 위로 위치 통일.</p>';footer.appendChild(log);}else log.hidden=!log.hidden;});}
})();

;
(function(){
 if(!document.body.classList.contains('kr'))return;
 var root=document.querySelector('#kr-stock>.wrap');if(!root)return;
 var tools=document.createElement('details');tools.className='cross-restricted cross-return-tools';tools.innerHTML='<summary>내 투자 도구 · 수익률 곡선</summary><p>코스피 벤치마크와 종목의 가격 수익률을 비교합니다. 배당·세금·환율은 포함하지 않습니다.</p><form><label>종목 코드 <input aria-label="한국주식 종목 코드" placeholder="예: 005930.KS" pattern="[0-9]{6}\\.(KS|KQ)" value="005930.KS" required></label><label>기간 <select aria-label="수익률 기간"><option value="12">1년</option><option value="36">3년</option><option value="60">5년</option><option value="120">10년</option></select></label><button type="submit">비교하기</button></form><div class="cross-return-chart" role="status" aria-live="polite">종목과 기간을 선택해 비교하세요.</div>';
 root.appendChild(tools);var form=tools.querySelector('form'),box=tools.querySelector('.cross-return-chart'),cache={};
 function cutoff(months){var now=new Date(),year=now.getFullYear(),month=now.getMonth()-months,day=now.getDate(),d=new Date(year,month,1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d.getTime()/1000;}
 async function load(sym){if(cache[sym])return cache[sym];var job=(async function(){var j=await getJSON('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(sym)+'?range=10y&interval=1d');var r=j&&j.chart&&j.chart.result&&j.chart.result[0],c=r&&r.indicators&&r.indicators.quote&&r.indicators.quote[0].close;if(!r||!c)throw Error('시세 없음');return r.timestamp.map(function(t,i){return {t:t,v:c[i],d:new Date(t*1000).toISOString().slice(0,10)};}).filter(function(x){return Number.isFinite(x.v)&&x.v>0;});})();cache[sym]=job;try{return await job;}catch(e){delete cache[sym];throw e;}}
 var seq=0;
 form.addEventListener('submit',async function(e){e.preventDefault();var sym=form.querySelector('input').value.trim().toUpperCase();if(!/^[0-9]{6}\.(KS|KQ)$/.test(sym)){box.textContent='6자리 종목 코드 뒤에 .KS 또는 .KQ를 입력하세요.';return;}var n=++seq;box.textContent='수익률을 불러오는 중…';try{var data=await Promise.all([load(sym),load('^KS11')]);if(n!==seq)return;var cut=cutoff(+form.querySelector('select').value),by=new Map(data[1].map(function(x){return[x.d,x];})),pairs=data[0].filter(function(x){return x.t>=cut&&by.has(x.d);});if(pairs.length<2)throw Error('해당 기간의 공통 거래일 부족');var baseA=pairs[0].v,baseB=by.get(pairs[0].d).v;var a=pairs.map(function(x){return(x.v/baseA-1)*100;}),b=pairs.map(function(x){return(by.get(x.d).v/baseB-1)*100;}),lo=Math.min(0,...a,...b),hi=Math.max(0,...a,...b);if(hi===lo){lo-=1;hi+=1;}var pad=(hi-lo)*.08;lo-=pad;hi+=pad;var W=760,H=310,L=62,R=20,T=20,D=56,pw=W-L-R,ph=H-T-D;var y=function(v){return T+(hi-v)/(hi-lo)*ph;},x=function(i){return L+i/(pairs.length-1)*pw;},path=function(v){return v.map(function(p,i){return(i?'L':'M')+x(i).toFixed(2)+' '+y(p).toFixed(2);}).join(' ');},ticks='';for(var i=0;i<5;i++){var v=lo+(hi-lo)*i/4,yy=y(v);ticks+='<line x1="'+L+'" x2="'+(W-R)+'" y1="'+yy+'" y2="'+yy+'" stroke="currentColor" opacity=".12"/><text x="'+(L-8)+'" y="'+(yy+4)+'" text-anchor="end">'+v.toFixed(1)+'%</text>';}[0,Math.floor((pairs.length-1)/2),pairs.length-1].forEach(function(i){ticks+='<text x="'+x(i)+'" y="'+(H-31)+'" text-anchor="middle">'+pairs[i].d+'</text>';});box.innerHTML='<div class="cross-return-legend"><b style="color:#16865c">● '+sym+' '+a[a.length-1].toFixed(2)+'%</b><b style="color:#4086dd">┄ 코스피 '+b[b.length-1].toFixed(2)+'%</b></div><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+sym+'와 코스피의 수익률 비교. 세로축 수익률 퍼센트, 가로축 날짜."><g fill="currentColor" font-size="11">'+ticks+'<text x="'+L+'" y="12">수익률(%)</text><text x="'+(W/2)+'" y="'+(H-6)+'" text-anchor="middle">날짜</text></g><path d="'+path(b)+'" fill="none" stroke="#4086dd" stroke-width="2" stroke-dasharray="6 3"/><path d="'+path(a)+'" fill="none" stroke="#16865c" stroke-width="2.5"/></svg><p>실제 공통 거래일: '+pairs[0].d+' ~ '+pairs[pairs.length-1].d+' · 상장 기간이나 공급처에 따라 선택 기간보다 짧을 수 있습니다.</p>';}catch(err){if(n===seq)box.textContent='수익률을 불러오지 못했습니다. 종목 코드와 데이터 연결을 확인해 주세요.';}});
 tools.querySelector('summary').addEventListener('click',function(e){if(tools.open)return;e.preventDefault();var fn=function(){tools.open=true;};if(window.MK_REQUEST_DETAIL)window.MK_REQUEST_DETAIL(fn);else fn();});
})();
